default:
  image: docker:20.10
  retry: 
    max: 2
    when:
     - stuck_or_timeout_failure

workflow:
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "staging" || $CI_PIPELINE_SOURCE == "merge_request_event" )
      when: always
    - when: never

stages:
  - release

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

connect-to-registry:
  stage: release
  before_script: 
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo "Connected to $CI_REGISTRY repository"

release-job:
  stage: release
  image: $CI_REGISTRY/emundus-semantic-release:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  script:
    - semantic-release
  artifacts:
    reports:
      dotenv: release.env
  only: 
    - master

sync-documentation-job:
  stage: release
  image: $CI_REGISTRY/emundus-sync-documentation:1.0.0
  script:
    - /go/generate-release-note.sh "$CI_SERVER_URL" "$CI_PROJECT_ID" "$GITLAB_TOKEN" "$ATLASSIAN_URL" "$ATLASSIAN_USER" "$ATLASSIAN_TOKEN" "$ATLASSIAN_SPACE" "$ATLASSIAN_PARENT_PAGE" "$ATLASSIAN_PAGE_TITLE"
  needs:
    - release-job
  only: 
    - master