version: '3.9'
services:
  web:
    container_name: web-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
    #image: emundus/tchooz-build-app:$CI_COMMIT_SHORT_SHA
    image: emundus/tchooz-build-app:latest
    restart: always
    environment:
      - TCHOOZ_OFFLINE=0
      - TCHOOZ_OFFLINE_MESSAGE=Offline
      - TCHOOZ_DISPLAY_OFFLINE_MESSAGE=1
      - TCHOOZ_OFFLINE_IMAGE=images/logo.png
      - TCHOOZ_SITENAME=Tchooz
      - TCHOOZ_EDITOR=tinymce
      - TCHOOZ_DEBUG=0
      - TCHOOZ_DEBUG_LANG=0
      - TCHOOZ_DB_HOST=tchooz-build-db
      - TCHOOZ_DB_USER=tchooz
      - TCHOOZ_DB_PASSWORD=tchooz_password
      - TCHOOZ_DB_NAME=vanilla
      - TCHOOZ_LIVE_SITE=
      - TCHOOZ_SECRET=${TCHOOZ_SECRET}
      - TCHOOZ_OFFSET=Europe/Paris
      - TCHOOZ_MAILER=smtp
      - TCHOOZ_MAIL_FROM=
      - TCHOOZ_MAIL_FROM_NAME=
      - TCHOOZ_MAIL_SMTP_AUTH=
      - TCHOOZ_MAIL_SMTP_USER=
      - TCHOOZ_MAIL_SMTP_PASS=
      - TCHOOZ_MAIL_SMTP_HOST=
      - TCHOOZ_MAIL_SMTP_SECURITY=
      - TCHOOZ_MAIL_SMTP_PORT=
      - TCHOOZ_CACHING=0
      - TCHOOZ_CACHE_HANDLER=redis
      - TCHOOZ_CACHE_LIFETIME=15
      - TCHOOZ_META_DESCRIPTION=Tchooz
      - TCHOOZ_META_KEYS=tchooz
      - TCHOOZ_LOG_PATH=/var/www/html/logs
      - TCHOOZ_TMP_PATH=/var/www/html/tmp
      - TCHOOZ_SESSION_LIFETIME=15
      - TCHOOZ_SESSION_HANDLER=redis
      - TCHOOZ_FORCE_SSL=0
      - TCHOOZ_REDIS_PERSIST=1
      - TCHOOZ_REDIS_HOST=redis
      - TCHOOZ_REDIS_PORT=6379
      - TCHOOZ_REDIS_DB=0
      - TCHOOZ_MAIL_REPLY_TO=
      - TCHOOZ_MAIL_REPLY_TO_NAME=
      - TCHOOZ_SESSION_REDIS_PERSIST=1
      - TCHOOZ_SESSION_REDIS_HOST=redis
      - TCHOOZ_SESSION_REDIS_PORT=6379
      - TCHOOZ_SESSION_REDIS_DB=0
      - TCHOOZ_PROSPECT=0
      - TCHOOZ_PLAN_LIMIT_APP_FORMS=0
      - TCHOOZ_PLAN_LIMIT_STORAGE_SPACE=0
      - TCHOOZ_PLAN_LIMIT_FORMS=0
      - TCHOOZ_BEHIND_LOADBALANCER=0
      - TCHOOZ_ADMIN_ACCESS_TOKEN=${TCHOOZ_ADMIN_ACCESS_TOKEN}
      - TCHOOZ_COORD_USERNAME=coordinator
      - TCHOOZ_COORD_MAIL=${TCHOOZ_COORD_MAIL}
      - TCHOOZ_COORD_FIRST_NAME=Coordinator
      - TCHOOZ_COORD_LAST_NAME=Tchooz
      - TCHOOZ_COORD_PASSWORD=${TCHOOZ_COORD_PASSWORD}
      - TCHOOZ_INSTANCE_ID=999999
      - TCHOOZ_CUSTOMER_ID=999999
    healthcheck:
      test: curl --fail -s http://web-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    # depends_on:
    #   database:
    #     condition: service_healthy
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    links:
      - database
      - redis
    # networks:
    #   - default

  # database:
  #   container_name: database-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
  #   image: emundus/tchooz-build-db:$CI_COMMIT_SHORT_SHA
  #   environment:
  #     - MYSQL_DATABASE=${TCHOOZ_DB_NAME}
  #     - MYSQL_USER=${TCHOOZ_DB_USER}
  #     - MYSQL_PASSWORD=${TCHOOZ_DB_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "mysql" ,"-h", "${TCHOOZ_DB_HOST}", "-P", "3306", "-u", "${TCHOOZ_DB_USER}", "-p${TCHOOZ_DB_PASSWORD}", "-e", "USE ${TCHOOZ_DB_NAME}; DESCRIBE language_requirements;"]
  #     interval: 5s
  #     retries: 30
  #     start_period: 1s
  #     timeout: 10s
  #   restart: always
  #   cap_add:
  #     - SYS_NICE
  #   networks:
  #     - default

  # redis:
  #   container_name: redis-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
  #   image: redis:latest
  #   restart: always
  #   networks:
  #     - default

# networks:
#   default:
#     name: tchooz-network-$CI_COMMIT_SHORT_SHA-$CI_JOB_ID
