<?php
	$_GET['option']='com_hikashop';
	$_GET['tmpl']='component';
	$_GET['ctrl']='checkout';
	$_GET['task']='notify';
	$_GET['notif_payment']='paybox';
	$_GET['format']='html';
	$_GET['lang']='fr';
	$_GET['notif_id']='3';
	$_REQUEST['option']='com_hikashop';
	$_REQUEST['tmpl']='component';
	$_REQUEST['ctrl']='checkout';
	$_REQUEST['task']='notify';
	$_REQUEST['notif_payment']='paybox';
	$_REQUEST['format']='html';
	$_REQUEST['lang']='fr';
	$_REQUEST['notif_id']='3';
	include('index.php');
