<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');

JText::script('COM_EMUNDUS_ONBOARD_FROM');
JText::script('COM_EMUNDUS_ONBOARD_ACTIONS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_ADD_FORM');
JText::script('COM_EMUNDUS_ONBOARD_TO');
JText::script('COM_EMUNDUS_ONBOARD_SINCE');
JText::script('COM_EMUNDUS_ONBOARD_MODIFY');
JText::script('COM_EMUNDUS_ONBOARD_CAMPAIGN');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_FORM');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_EVALUATOR_GROUP');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_EMAIL_TRIGGER');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_EVALUATION_GRID');
JText::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
JText::script('COM_EMUNDUS_ONBOARD_ADD_CONTINUER');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_STARTDATE');
JText::script('COM_EMUNDUS_ONBOARD_FORMDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_ENDDATE');
JText::script('COM_EMUNDUS_ONBOARD_DOCSDESCRIPTION');
JText::script('CREATE');
JText::script('RETRIEVE');
JText::script('UPDATE');
JText::script('DELETE');
JText::script('BACK');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_PROFILE_WARNING');
JText::script('COM_EMUNDUS_ONBOARD_WARNING');
JText::script('COM_EMUNDUS_ONBOARD_FORM_AFFECTEDFILES');
JText::script('COM_EMUNDUS_ONBOARD_DUPLICATE');
JText::script('COM_EMUNDUS_ONBOARD_CREATE_DOCUMENT');
JText::script('COM_EMUNDUS_ONBOARD_LASTNAME');
JText::script('COM_EMUNDUS_ONBOARD_OK');
JText::script('COM_EMUNDUS_ONBOARD_MAXPERUSER');
JText::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED');
JText::script('COM_EMUNDUS_ONBOARD_FILE_SIZE');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_LABEL');
JText::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_MAXPERUSER_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEDOCUMENTTYPE');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEDOCUMENTTYPE_MESSAGE');
JText::script('COM_EMUNDUS_ONBOARD_CANCEL');
JText::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
JText::script('COM_EMUNDUS_ONBOARD_SUBMITTIONDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_PDF_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_PICTURES_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_OFFICE_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_EXCEL_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_TRANSLATE_IN');
JText::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD');
JText::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD_CONFIRMATION');
JText::script('COM_EMUNDUS_ONBOARD_REMOVE_FILE');
JText::script('COM_EMUNDUS_ONBOARD_INVALID_FILE_TYPE');
JText::script('COM_EMUNDUS_ONBOARD_FILE_TOO_BIG');
JText::script('COM_EMUNDUS_ONBOARD_MAX_FILES_EXCEEDED');
JText::script('COM_EMUNDUS_ONBOARD_DROP_FILE_HERE');
JText::script('COM_EMUNDUS_ONBOARD_ERROR');
JText::script('COM_EMUNDUS_ONBOARD_DOCUMENT_NAME');
JText::script('COM_EMUNDUS_ONBOARD_FORM_PAGE');
JText::script('COM_EMUNDUS_ONBOARD_FORM');
JText::script('COM_EMUNDUS_ONBOARD_DOCUMENT_ASSIGNED_TO_FORM');
JText::script('COM_EMUNDUS_ONBOARD_DOCUMENT_NO_ASSIGNED_TO_FORM');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_WARNING');
JText::script('COM_EMUNDUS_ONBOARD_EDIT_DOCUMENT');
JText::script('COM_EMUNDUS_ONBOARD_REMOVE_DOCUMENT');
JText::script('COM_EMUNDUS_ONBOARD_ADD_DOCUMENT');
JText::script('COM_EMUNDUS_ONBOARD_DELETE_DOCUMENT');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_INTRO_DESC');

JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PARAMETER');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CAMPNAME');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_INFORMATION');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_RESUME');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CHOOSEPROG');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PICKYEAR');
JText::script('COM_EMUNDUS_ONBOARD_ADDPROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_ADD_QUITTER');
JText::script('COM_EMUNDUS_ONBOARD_FILTER_PUBLISH');
JText::script('COM_EMUNDUS_ONBOARD_FILTER_CLOSE');
JText::script('COM_EMUNDUS_ONBOARD_DEPOTDEDOSSIER');
JText::script('COM_EMUNDUS_ONBOARD_PROGNAME');
JText::script('COM_EMUNDUS_ONBOARD_PROGCODE');
JText::script('COM_EMUNDUS_ONBOARD_PROGCOLOR');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_NAMECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
JText::script('COM_EMUNDUS_ONBOARD_REQUIRED_FIELDS_INDICATE');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_RESUME');
JText::script('COM_EMUNDUS_ONBOARD_CAMP_REQUIRED_RESUME');
JText::script('COM_EMUNDUS_ONBOARD_TIP');
JText::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT');
JText::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_NUMBER');
JText::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_STATUS');
JText::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRANSLATETIP');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_REMOVETRIGGER');
JText::script("COM_EMUNDUS_CAMPAIGN_ONGOING");
JText::script("COM_EMUNDUS_CAMPAIGN_YET_TO_COME");

## FORMS ##
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CHOOSEPROG');
JText::script('COM_EMUNDUS_ONBOARD_ADDPROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_PROGNAME');
JText::script('COM_EMUNDUS_ONBOARD_PROGCODE');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_NAMECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_EDITOR_UNDO');
JText::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
JText::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CODE');
JText::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_REQUIRED_FIELDS_INDICATE');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_RESUME');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CODE');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADDUSER');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
JText::script('COM_EMUNDUS_ONBOARD_FIRSTNAME');
JText::script('COM_EMUNDUS_ONBOARD_FIRSTNAME_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_LASTNAME');
JText::script('COM_EMUNDUS_ONBOARD_LASTNAME_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_PSEUDO_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_ROLE');
JText::script('COM_EMUNDUS_ONBOARD_ROLE_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_NAME');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_INTRO');
JText::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
JText::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
JText::script('COM_EMUNDUS_ONBOARD_SAVE_AS_TEMPLATE');
JText::script('COM_EMUNDUS_ONBOARD_DOCUMENTS');
JText::script('COM_EMUNDUS_OR');

## DESCRIPTION ##
JText::script('COM_EMUNDUS_ONBOARD_USERSDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_VISIBILITYDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_EMAILSDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_MANUAL_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_EVALUATIONGRIDDESCRIPTION');
## END ##

## TRIGGERS ##
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_ADDTRIGGER');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_AFFECTTRIGGERS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGER_CHOOSE_USERS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGER_USERS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_PREVIEWMODEL');
JText::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE');
JText::script('COM_EMUNDUS_ONBOARD_MANUAL');
JText::script('COM_EMUNDUS_ONBOARD_CHANGED_ACTION_STATUS');
JText::script('COM_EMUNDUS_ONBOARD_CANDIDATE_ACTION');
JText::script('COM_EMUNDUS_ONBOARD_MANAGER_ACTION');
JText::script('COM_EMUNDUS_ADD_TRIGGER_MISSING_EMAIL_MODELS');
## END ##

## USERS ##
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATORS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATORS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATOR');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATOR');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_USERSEMPTY');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CANDIDATES');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_DEFINED_USERS');
JText::script('COM_EMUNDUS_ONBOARD_SEARCH_USERS');
## END ##

## EVALUATION ##
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN_WARNING');
JText::script('COM_EMUNDUS_ONBOARD_NO_AFFECTED_FORM');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGROUP');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGRID');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_EDITGRID');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGRID');
JText::script('COM_EMUNDUS_ONBOARD_GRIDMODEL');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGRID_QUESTION');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_GRIDDELETED');
## END ##

## TUTORIAL ##
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_CAMPAIGN');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORM');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORMBUILDER');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_PROGRAM');
JText::script('COM_EMUNDUS_ADD_CAMPAIGN_ERROR');
## END ##

JText::script('DATE_FORMAT_JS_LC2');

JText::script('COM_EMUNDUS_FORM_CAMPAIGN');
JText::script('COM_EMUNDUS_DOCUMENTS_CAMPAIGNS');
JText::script('COM_EMUNDUS_GLOBAL_INFORMATIONS');
JText::script('COM_EMUNDUS_FORM_CAMPAIGN_DESC');
JText::script('COM_EMUNDUS_DOCUMENTS_CAMPAIGNS_DESC');
JText::script('COM_EMUNDUS_GLOBAL_INFORMATIONS_DESC');
JText::script('COM_EMUNDUS_EMAILS');
JText::script('COM_EMUNDUS_EMAILS_DESC');
JText::script('COM_EMUNDUS_FORM_BUILDER_SECTION');
JText::script('COM_EMUNDUS_FORM_PAGES_PREVIEW');
JText::script('COM_EMUNDUS_FORM_ATTACHMENTS_PREVIEW');
JText::script('COM_EMUNDUS_ONBOARD_NO_FORM_FOUND_ADD_FORM');
JText::script('COM_EMUNDUS_ONBOARD_EDIT_FORM');

$lang = JFactory::getLanguage();
$short_lang = substr($lang->getTag(), 0 , 2);
$current_lang = $lang->getTag();
$languages = JLanguageHelper::getLanguages();
if (count($languages) > 1) {
    $many_languages = '1';
    require_once JPATH_SITE . '/components/com_emundus/models/translations.php';
    $m_translations = new EmundusModelTranslations();
    $default_lang = $m_translations->getDefaultLanguage()->lang_code;
} else {
    $many_languages = '0';
    $default_lang = $current_lang;
}

$user = JFactory::getUser();
$coordinator_access = EmundusHelperAccess::asCoordinatorAccessLevel($user->id);
$sysadmin_access = EmundusHelperAccess::isAdministrator($user->id);

$xmlDoc = new DOMDocument();
if ($xmlDoc->load(JPATH_SITE.'/administrator/components/com_emundus/emundus.xml')) {
    $release_version = $xmlDoc->getElementsByTagName('version')->item(0)->textContent;
}
?>

<div id="em-component-vue"
     component="addformnextcampaign"
     campaignId="<?= JFactory::getApplication()->input->get('cid') ?>"
     shortLang="<?= $short_lang ?>" currentLanguage="<?= $current_lang ?>"
     manyLanguages="<?= $many_languages ?>"
     defaultLang="<?= $default_lang ?>"
     coordinatorAccess="<?= $coordinator_access ?>"
     sysadminAccess="<?= $sysadmin_access ?>"
     index="<?= JFactory::getApplication()->input->get('index') ?>"
></div>

<script src="media/com_emundus_vue/app_emundus.js?<?php echo $release_version ?>"></script>
