<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Language\LanguageHelper;

Text::script('COM_EMUNDUS_ONBOARD_FROM');
Text::script('COM_EMUNDUS_ONBOARD_ACTIONS_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_ADD_FORM');
Text::script('COM_EMUNDUS_ONBOARD_TO');
Text::script('COM_EMUNDUS_ONBOARD_SINCE');
Text::script('COM_EMUNDUS_ONBOARD_MODIFY');
Text::script('COM_EMUNDUS_ONBOARD_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_FORM');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_EVALUATOR_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_EMAIL_TRIGGER');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_EVALUATION_GRID');
Text::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTINUER');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_STARTDATE');
Text::script('COM_EMUNDUS_ONBOARD_FORMDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_ENDDATE');
Text::script('COM_EMUNDUS_ONBOARD_DOCSDESCRIPTION');
Text::script('CREATE');
Text::script('RETRIEVE');
Text::script('UPDATE');
Text::script('DELETE');
Text::script('BACK');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_PROFILE_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_FORM_AFFECTEDFILES');
Text::script('COM_EMUNDUS_ONBOARD_DUPLICATE');
Text::script('COM_EMUNDUS_ONBOARD_CREATE_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME');
Text::script('COM_EMUNDUS_ONBOARD_OK');
Text::script('COM_EMUNDUS_ONBOARD_MAXPERUSER');
Text::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED');
Text::script('COM_EMUNDUS_ONBOARD_FILE_SIZE');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_MAXPERUSER_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEDOCUMENTTYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEDOCUMENTTYPE_MESSAGE');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
Text::script('COM_EMUNDUS_ONBOARD_SUBMITTIONDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_PDF_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_PICTURES_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_OFFICE_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_EXCEL_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_IN');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL_UPLOAD_CONFIRMATION');
Text::script('COM_EMUNDUS_ONBOARD_REMOVE_FILE');
Text::script('COM_EMUNDUS_ONBOARD_INVALID_FILE_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_FILE_TOO_BIG');
Text::script('COM_EMUNDUS_ONBOARD_MAX_FILES_EXCEEDED');
Text::script('COM_EMUNDUS_ONBOARD_DROP_FILE_HERE');
Text::script('COM_EMUNDUS_ONBOARD_ERROR');
Text::script('COM_EMUNDUS_ONBOARD_DOCUMENT_NAME');
Text::script('COM_EMUNDUS_ONBOARD_FORM_PAGE');
Text::script('COM_EMUNDUS_ONBOARD_FORM');
Text::script('COM_EMUNDUS_ONBOARD_DOCUMENT_ASSIGNED_TO_FORM');
Text::script('COM_EMUNDUS_ONBOARD_DOCUMENT_NO_ASSIGNED_TO_FORM');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_EDIT_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_REMOVE_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_DELETE_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_INTRO_DESC');

Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PARAMETER');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CAMPNAME');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_INFORMATION');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_RESUME');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CHOOSEPROG');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PICKYEAR');
Text::script('COM_EMUNDUS_ONBOARD_ADDPROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_ADD_QUITTER');
Text::script('COM_EMUNDUS_ONBOARD_FILTER_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_FILTER_CLOSE');
Text::script('COM_EMUNDUS_ONBOARD_DEPOTDEDOSSIER');
Text::script('COM_EMUNDUS_ONBOARD_PROGNAME');
Text::script('COM_EMUNDUS_ONBOARD_PROGCODE');
Text::script('COM_EMUNDUS_ONBOARD_PROGCOLOR');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSECATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_NAMECATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
Text::script('COM_EMUNDUS_ONBOARD_REQUIRED_FIELDS_INDICATE');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_RESUME');
Text::script('COM_EMUNDUS_ONBOARD_CAMP_REQUIRED_RESUME');
Text::script('COM_EMUNDUS_ONBOARD_TIP');
Text::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT');
Text::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_FILES_LIMIT_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATETIP');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_REMOVETRIGGER');
Text::script("COM_EMUNDUS_CAMPAIGN_ONGOING");
Text::script("COM_EMUNDUS_CAMPAIGN_YET_TO_COME");

## FORMS ##
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CHOOSEPROG');
Text::script('COM_EMUNDUS_ONBOARD_ADDPROGRAM');
Text::script('COM_EMUNDUS_ONBOARD_PROGNAME');
Text::script('COM_EMUNDUS_ONBOARD_PROGCODE');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSECATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_NAMECATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_EDITOR_UNDO');
Text::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
Text::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CODE');
Text::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_REQUIRED_FIELDS_INDICATE');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_RESUME');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_CODE');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_CATEGORY');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADDUSER');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
Text::script('COM_EMUNDUS_ONBOARD_FIRSTNAME');
Text::script('COM_EMUNDUS_ONBOARD_FIRSTNAME_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_PSEUDO_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_ROLE');
Text::script('COM_EMUNDUS_ONBOARD_ROLE_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_FIELD_NAME');
Text::script('COM_EMUNDUS_ONBOARD_FIELD_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
Text::script('COM_EMUNDUS_ONBOARD_SAVE_AS_TEMPLATE');
Text::script('COM_EMUNDUS_ONBOARD_DOCUMENTS');
Text::script('COM_EMUNDUS_OR');

## DESCRIPTION ##
Text::script('COM_EMUNDUS_ONBOARD_USERSDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_VISIBILITYDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_EMAILSDESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_MANUAL_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_EVALUATIONGRIDDESCRIPTION');
## END ##

## TRIGGERS ##
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_ADDTRIGGER');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_AFFECTTRIGGERS');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGER_CHOOSE_USERS');
Text::script('COM_EMUNDUS_ONBOARD_TRIGGER_USERS_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_EMAIL_PREVIEWMODEL');
Text::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE');
Text::script('COM_EMUNDUS_ONBOARD_MANUAL');
Text::script('COM_EMUNDUS_ONBOARD_CHANGED_ACTION_STATUS');
Text::script('COM_EMUNDUS_ONBOARD_CANDIDATE_ACTION');
Text::script('COM_EMUNDUS_ONBOARD_MANAGER_ACTION');
Text::script('COM_EMUNDUS_ADD_TRIGGER_MISSING_EMAIL_MODELS');
## END ##

## USERS ##
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATORS');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATORS');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATOR');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATOR');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_USERSEMPTY');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_CANDIDATES');
Text::script('COM_EMUNDUS_ONBOARD_PROGRAM_DEFINED_USERS');
Text::script('COM_EMUNDUS_ONBOARD_SEARCH_USERS');
## END ##

## EVALUATION ##
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN_WARNING');
Text::script('COM_EMUNDUS_ONBOARD_NO_AFFECTED_FORM');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGROUP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGRID');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EDITGRID');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGRID');
Text::script('COM_EMUNDUS_ONBOARD_GRIDMODEL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGRID_QUESTION');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_GRIDDELETED');
## END ##

## TUTORIAL ##
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORM');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORMBUILDER');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_PROGRAM');
Text::script('COM_EMUNDUS_ADD_CAMPAIGN_ERROR');
## END ##

Text::script('DATE_FORMAT_JS_LC2');

Text::script('COM_EMUNDUS_FORM_CAMPAIGN');
Text::script('COM_EMUNDUS_DOCUMENTS_CAMPAIGNS');
Text::script('COM_EMUNDUS_GLOBAL_INFORMATIONS');
Text::script('COM_EMUNDUS_FORM_CAMPAIGN_DESC');
Text::script('COM_EMUNDUS_DOCUMENTS_CAMPAIGNS_DESC');
Text::script('COM_EMUNDUS_GLOBAL_INFORMATIONS_DESC');
Text::script('COM_EMUNDUS_EMAILS');
Text::script('COM_EMUNDUS_EMAILS_DESC');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTION');
Text::script('COM_EMUNDUS_FORM_PAGES_PREVIEW');
Text::script('COM_EMUNDUS_FORM_ATTACHMENTS_PREVIEW');
Text::script('COM_EMUNDUS_ONBOARD_NO_FORM_FOUND_ADD_FORM');
Text::script('COM_EMUNDUS_ONBOARD_EDIT_FORM');

$app = Factory::getApplication();
if (version_compare(JVERSION, '4.0', '>')) {
	$lang = $app->getLanguage();
	$user = $app->getIdentity();
}
else {
	$lang = Factory::getLanguage();
	$user = Factory::getUser();
}

$short_lang   = substr($lang->getTag(), 0, 2);
$current_lang = $lang->getTag();
$languages    = LanguageHelper::getLanguages();
if (count($languages) > 1) {
	$many_languages = '1';
	require_once JPATH_SITE . '/components/com_emundus/models/translations.php';
	$m_translations = new EmundusModelTranslations();
	$default_lang   = $m_translations->getDefaultLanguage()->lang_code;
}
else {
	$many_languages = '0';
	$default_lang   = $current_lang;
}

$coordinator_access = EmundusHelperAccess::asCoordinatorAccessLevel($user->id);
$sysadmin_access    = EmundusHelperAccess::isAdministrator($user->id);

require_once(JPATH_BASE . DS . 'components' . DS . 'com_emundus' . DS . 'helpers' . DS . 'cache.php');
$hash = EmundusHelperCache::getCurrentGitHash();
?>

<div id="em-component-vue"
     component="addformnextcampaign"
     campaignId="<?= $app->input->get('cid') ?>"
     shortLang="<?= $short_lang ?>" currentLanguage="<?= $current_lang ?>"
     manyLanguages="<?= $many_languages ?>"
     defaultLang="<?= $default_lang ?>"
     coordinatorAccess="<?= $coordinator_access ?>"
     sysadminAccess="<?= $sysadmin_access ?>"
     index="<?= $app->input->get('index') ?>"
></div>

<script src="media/com_emundus_vue/app_emundus.js?<?php echo $hash ?>"></script>
