language: php

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update

install:
    - composer update --prefer-source --no-interaction --no-progress --no-suggest $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --exclude-group functional
