#INSERT INTO jos_extensions (package_id, name, type, element, folder, client_id, enabled, access, protected, manifest_cache, params, custom_data, system_data, checked_out, checked_out_time, ordering, state)
#VALUES (0, 'MOD_EMUNDUS_HOMEPAGE', 'module', 'mod_emundus_homepage', '', 0, 1, 1, 0, '{"name":"MOD_EMUNDUS_HOMEPAGE","type":"module","creationDate":"June 2022","author":"eMundus","copyright":"Copyright (C) eMundus. All rights reserved.","authorEmail":"brice.hubinet@emundus.fr","authorUrl":"www.emundus.fr","version":"1.0.0","description":"MOD_EMUNDUS_HOMEPAGE_XML_DESCRIPTION","group":"","filename":"mod_emundus_homepage"}', '{}', '', '', 0, '2022-05-30 15:04:28', 0, 0);

INSERT INTO jos_modules (asset_id, title, note, content, ordering, position, checked_out, checked_out_time, publish_up, publish_down, published, module, access, showtitle, params, client_id, language)
VALUES (403, 'Page d''accueil', '', null, 1, 'content-bottom-a', 0, '2022-02-22 16:28:57', '2022-02-22 16:28:57', '2099-02-22 16:28:57', 1, 'mod_emundus_homepage', 1, 0, '{"mod_em_homepage_sections":["banner","filters","introtext","campaigns"],"mod_em_homepage_banner_image":"images\/custom\/banner.png","mod_em_homepage_banner_text":"","mod_em_homepage_banner_opacity":"50","mod_em_homepage_filters_display":["keywords","category","program","state"],"mod_em_homepage_introtext_text":"","mod_em_homepage_list_display":["current","future"],"mod_em_homepage_list_program_category":"1","mod_em_homepage_list_program":"1","mod_em_homepage_list_timezone":"0","mod_em_homepage_list_start_date_display":"daily_count","mod_em_homepage_list_end_date_display":"1","mod_em_homepage_list_text_display":["short_description"],"mod_em_homepage_list_more_informations_display":"1","mod_em_homepage_list_alerting_display":"0","mod_em_homepage_list_pinned_campaign_display":"1","mod_em_homepage_details_tabs":["informations","faq","available_attachments","contact"],"mod_em_homepage_details_text":["description"],"mod_em_homepage_details_start_date_display":"1","mod_em_homepage_details_end_date_display":"1","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*');
SEt @module_id = LAST_INSERT_ID();

INSERT INTO jos_modules_menu (moduleid, menuid) VALUES (@module_id, 1079);

UPDATE jos_modules SET published = 0 WHERE module LIKE 'mod_emundus_campaign';
