name: _error
timestamp: 1635347996
version: 7
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: _joomla_-_gantry4
  timestamp: 1530009501
positions:
  top-b: 'Top B'
  top-c: 'Top C'
  header-a: 'Header A'
  header-b: Header-b
  header-c: 'Header C'
  breadcrumb: Breadcrumb
  drawer: Drawer
  drawer-a: 'Drawer A'
  drawer-b: 'Drawer B'
  drawer-c: 'Drawer C'
  sidebar-a: 'Sidebar A'
  sidebar-b: 'Sidebar B'
  sidebar-c: 'Sidebar C'
  bottom-a: bottom-a
  bottom-b: bottom-b
  bottom-c: bottom-c
  footer-a: footer-a
  footer-b: footer-b
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  utility: Utility
  breadcrumb: Breadcrumb
  maintop: Maintop
  mainbottom: Mainbottom
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  main-mainbody: Mainbody
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-4537: 'Top B'
    position-position-5618: 'Top C'
    position-position-2758: 'Header A'
    position-position-4458: Header-b
    position-position-6420: 'Header C'
    position-position-2966: Breadcrumb
    position-position-3690: Drawer
    position-position-7693: 'Drawer A'
    position-position-5955: 'Drawer B'
    position-position-1889: 'Drawer C'
    position-position-2695: 'Sidebar A'
    position-position-1010: 'Sidebar B'
    position-position-2875: 'Sidebar C'
    position-position-9568: bottom-a
    position-position-1552: bottom-b
    position-position-3410: bottom-c
    position-position-7211: footer-a
    position-position-3802: footer-b
  messages:
    system-messages-2171: 'System Messages'
  custom:
    custom-5609: 'Custom HTML'
  module:
    position-module-7703: 'Mobile Menu'
    position-module-7526: 'User menu phone'
inherit:
  default:
    drawer: drawer
    top: top
    position-position-4537: position-position-4408
    position-position-5618: position-position-7532
    navigation: navigation
    position-position-2758: position-position-6276
    position-position-4458: position-position-5691
    position-position-6420: position-position-5235
    showcase: showcase
    position-position-2966: position-position-6366
    feature: feature
    system-messages-2171: system-messages-7972
    utility: utility
    position-position-3690: position-position-6313
    position-position-7693: position-position-3312
    position-position-5955: position-position-3137
    position-position-1889: position-position-3100
    breadcrumb: breadcrumb
    maintop: maintop
    sidebar: sidebar
    position-position-2695: position-position-8186
    position-position-1010: position-position-9360
    position-position-2875: position-position-3949
    mainbottom: mainbottom
    extension: extension
    bottom: bottom
    position-position-9568: position-position-3854
    position-position-1552: position-position-8649
    position-position-3410: position-position-5181
    footer: footer
    position-position-7211: position-position-6744
    position-position-3802: position-position-8794
    copyright: copyright
    offcanvas: offcanvas
    position-module-7703: position-module-2455
    position-module-7526: position-module-3093
