#!/bin/sh

echo "***** Compile Tailwind CSS ******"
npm run build && git add templates/g5_helium/custom/scss/main.compiled.css

echo "***** Build VueJS files ******"

status=$(git status -s --untracked-files=no | grep 'components/com_emundus/' | grep '.vue' | echo $?)
echo $status;
if [ "$status" -eq 0 ]; then
    echo "***** VueJS files changed ******"

    cd components/com_emundus && yarn run build && cd ../.. && git add media/com_emundus_vue/
    git add media/com_emundus_vue/app_emundus.js
    git add media/com_emundus_vue/chunk-vendors_emundus.css
    git add media/com_emundus_vue/chunk-vendors_emundus.js
else
    echo "***** No VueJS files changed ******"
fi

exit 0;

