SELECT @group_id := jff.group_id
FROM jos_fabrik_formgroup AS jff
LEFT JOIN jos_fabrik_lists AS jfl ON jfl.form_id = jff.form_id
WHERE jfl.db_table_name LIKE 'jos_emundus_campaign_workflow';

INSERT INTO jos_fabrik_elements (name, group_id, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params)
VALUES ('label', @group_id, 'field', 'Nom de la phase', 0, '2022-10-05 20:31:36', '2022-10-05 20:31:36', 62, 'sysadmin', '2022-10-05 20:31:36', 0, 0, 0, '', 0, 0, 5, 0, '', 1, 1, 0, 0, 0, 1, 0, 0, '{"placeholder":"","password":"0","maxlength":"255","disable":"0","readonly":"0","autocomplete":"1","speech":"0","advanced_behavior":"0","bootstrap_class":"input-medium","text_format":"text","integer_length":"11","decimal_length":"2","field_use_number_format":"0","field_thousand_sep":",","field_decimal_sep":".","text_format_string":"","field_format_string_blank":"1","text_input_mask":"","text_input_mask_autoclear":"0","text_input_mask_definitions":"","render_as_qrcode":"0","scan_qrcode":"0","guess_linktype":"0","link_target_options":"default","rel":"","link_title":"","link_attributes":"","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","notempty-message":[""],"notempty-validation_condition":[""],"tip_text":[""],"icon":[""],"validations":{"plugin":["notempty"],"plugin_published":["1"],"validate_in":["both"],"validation_on":["both"],"validate_hidden":["0"],"must_validate":["0"],"show_icon":["1"]}}');
INSERT INTO jos_fabrik_elements (name, group_id, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params)
VALUES ('form_id', @group_id, 'databasejoin', 'Formulaire', 0, '2022-10-05 20:31:36', '2022-10-05 20:14:57', 62, 'sysadmin', '2022-10-05 20:31:01', 62, 0, 0, '', 0, 0, 7, 0, '', 1, 1, 0, 0, 0, 1, 0, 0, '{"database_join_display_type":"dropdown","join_conn_id":"1","join_db_name":"jos_emundus_setup_formlist","join_key_column":"form_id","join_val_column":"form_id","join_val_column_concat":"(select ff.label from jos_fabrik_forms ff where ff.id = {thistable}.form_id)","database_join_where_sql":"WHERE {thistable}.type = ''review''","database_join_where_access":"1","database_join_where_access_invert":"0","database_join_where_when":"3","databasejoin_where_ajax":"0","databasejoin_where_ajax_default_eval":"","database_join_filter_where_sql":"","database_join_show_please_select":"1","database_join_noselectionvalue":"","database_join_noselectionlabel":"","placeholder":"","databasejoin_popupform":"","fabrikdatabasejoin_frontend_add":"0","join_popupwidth":"","databasejoin_readonly_link":"0","fabrikdatabasejoin_frontend_select":"0","advanced_behavior":"0","dbjoin_options_per_row":"4","dbjoin_multiselect_max":"0","dbjoin_multilist_size":"6","dbjoin_autocomplete_size":"20","dbjoin_autocomplete_rows":"10","bootstrap_class":"input-large","dabase_join_label_eval":"","join_desc_column":"","dbjoin_autocomplete_how":"contains","clean_concat":"0","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","notempty-message":[""],"notempty-validation_condition":[""],"tip_text":[""],"icon":[""],"validations":{"plugin":["notempty"],"plugin_published":["1"],"validate_in":["both"],"validation_on":["both"],"validate_hidden":["0"],"must_validate":["0"],"show_icon":["1"]}}');
SET @formid_elt = LAST_INSERT_ID();
INSERT INTO jos_fabrik_elements (name, group_id, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params)
VALUES ('type', @group_id, 'radiobutton', 'Type de phase', 0, '2022-10-05 20:31:36', '2022-10-05 20:12:01', 62, 'sysadmin', '2022-10-05 20:30:37', 62, 0, 0, '', 0, 0, 4, 1, 'dropdown', 1, 1, 0, 0, 0, 1, 0, 0, '{"sub_options":{"sub_values":["1","2"],"sub_labels":["D\\u00e9posant","Examen du dossier"],"sub_initial_selection":["1"]},"options_per_row":"1","btnGroup":"0","allow_frontend_addtoradio":"0","rad-allowadd-onlylabel":"0","rad-savenewadditions":"0","dropdown_populate":"","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","validations":[]}');
SET @type_elt = LAST_INSERT_ID();

INSERT INTO jos_fabrik_joins (list_id, element_id, join_from_table, table_join, table_key, table_join_key, join_type, group_id, params)
VALUES (0, @formid_elt, '', 'jos_emundus_setup_formlist', 'form_id', 'form_id', 'left', @group_id, '{"join-label":"form_id","type":"element","pk":"`jos_emundus_setup_formlist`.`id`"}');

INSERT INTO jos_fabrik_jsactions (element_id, action, code, params)
VALUES (@type_elt, 'change', 'var value = this.get(&#039;value&#039;);
var fab = this.form.elements;

if(value == 1) {
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___form_id&#039;), clearElements = true);
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___output_status&#039;), clearElements = true);
  showFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___profile&#039;));
} else if(value == 2){
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___profile&#039;), clearElements = true);
  showFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___form_id&#039;));
}', '{"js_e_event":"","js_e_trigger":"fabrik_trigger_group_group760","js_e_condition":"","js_e_value":"","js_published":"1"}');
INSERT INTO jos_fabrik_jsactions (element_id, action, code, params)
VALUES (@type_elt, 'load', 'var value = this.get(&#039;value&#039;);
var fab = this.form.elements;

if(value == 1) {
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___form_id&#039;), clearElements = false);
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___output_status&#039;), clearElements = false);
  showFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___profile&#039;));
} else if(value == 2){
  hideFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___profile&#039;), clearElements = false);
  showFabrikElt(fab.get(&#039;jos_emundus_campaign_workflow___form_id&#039;));
}', '{"js_e_event":"","js_e_trigger":"fabrik_trigger_group_group760","js_e_condition":"","js_e_value":"","js_published":"1"}');


ALTER TABLE jos_emundus_campaign_workflow
    ADD label varchar(255) NULL AFTER updated;

ALTER TABLE jos_emundus_campaign_workflow
    ADD type int default 1 NULL;

ALTER TABLE jos_emundus_campaign_workflow
    ADD form_id int NULL;
