create table data_nationality
(
    id       int auto_increment primary key,
    label_fr varchar(255) null,
    label_en varchar(255) null
) engine = MyISAM;

INSERT INTO data_nationality (id, label_fr, label_en) VALUES (1, 'Afghane', 'Afghan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (2, 'Albanaise', 'Albanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (3, 'Algérienne', 'Algerian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (4, 'Allemande', 'German');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (5, 'Americaine', 'American');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (6, 'Andorrane', 'Andorran');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (7, 'Angolaise', 'Angolan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (8, 'Antiguaise-et-barbudienne', 'Antiguan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (9, 'Argentine', 'Argentinian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (10, 'Armenienne', 'Armenian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (11, 'Australienne', 'Australian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (12, 'Autrichienne', 'Austrian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (13, 'Azerbaïdjanaise', 'Azerbaijani');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (14, 'Bahamienne', 'Bahamian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (15, 'Bahreinienne', 'Bahraini');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (16, 'Bangladaise', 'Bangladeshi');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (17, 'Barbadienne', 'Barbadian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (18, 'Belge', 'Belgian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (19, 'Belizienne', 'Belizean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (20, 'Béninoise', 'Beninese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (21, 'Bhoutanaise', 'Bhutanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (22, 'Biélorusse', 'Belarussian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (23, 'Birmane', 'Burmese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (24, 'Bissau-guinéenne', 'Bissau-guinean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (25, 'Bolivienne', 'Bolivian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (26, 'Bosnienne', 'Bosnian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (27, 'Botswanaise', 'Botswanan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (28, 'Brésilienne', 'Brazilian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (29, 'Britannique', 'British');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (30, 'Brunéienne', 'Bruneian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (31, 'Bulgare', 'Bulgarian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (32, 'Burkinabée', 'Burkinabe');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (33, 'Burundaise', 'Burundian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (34, 'Cambodgienne', 'Cambodian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (35, 'Camerounaise', 'Cameroonian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (36, 'Canadienne', 'Canadian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (37, 'Cap-verdienne', 'Cape verdean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (38, 'Centrafricaine', 'Central african');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (39, 'Chilienne', 'Chilean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (40, 'Chinoise', 'Chinese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (41, 'Chypriote', 'Cypriot');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (42, 'Colombienne', 'Colombian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (43, 'Comorienne', 'Comorian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (44, 'Congolaise', 'Congolese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (45, 'Congolaise (rdc)', 'Congolese (drc)');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (46, 'Cookienne', 'Cookian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (47, 'Costaricaine', 'Costa rican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (48, 'Croate', 'Croatian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (49, 'Cubaine', 'Cuban');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (50, 'Danoise', 'Danish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (51, 'Djiboutienne', 'Djiboutian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (52, 'Dominicaine', 'Dominican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (53, 'Dominiquaise', 'Dominiquais');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (54, 'Égyptienne', 'Egyptian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (55, 'Émirienne', 'Emirati');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (56, 'Équato-guineenne', 'Equatorial guinean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (57, 'Équatorienne', 'Ecuadorian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (58, 'Érythréenne', 'Etritrean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (59, 'Espagnole', 'Spanish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (60, 'Est-timoraise', 'East timorese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (61, 'Estonienne', 'Estonian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (62, 'Éthiopienne', 'Ethiopian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (63, 'Fidjienne', 'Fidji');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (64, 'Finlandaise', 'Finnish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (65, 'Française', 'French');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (66, 'Gabonaise', 'Gabonese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (67, 'Gambienne', 'Gambian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (68, 'Georgienne', 'Georgian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (69, 'Ghanéenne', 'Ghanaian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (70, 'Gibraltarienne', 'Gibraltarian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (71, 'Grecque', 'Greek');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (72, 'Grenadienne', 'Grenadin');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (73, 'Groenlandaise', 'Greenlandic');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (74, 'Guatémaltèque', 'Guatemalan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (75, 'Guinéenne', 'Guinean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (76, 'Guyanienne', 'Guyanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (77, 'Haïtienne', 'Haitian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (78, 'Hondurienne', 'Honduran');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (79, 'Hongroise', 'Hungarian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (80, 'Indienne', 'Indian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (81, 'Indonésienne', 'Indonesia');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (82, 'Irakienne', 'Iraqi');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (83, 'Iranienne', 'Iranian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (84, 'Irlandaise', 'Irish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (85, 'Irlandaise du nord', 'Northern irish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (86, 'Islandaise', 'Icelandic');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (87, 'Israélienne', 'Israeli');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (88, 'Italienne', 'Italian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (89, 'Ivoirienne', 'Ivorian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (90, 'Jamaïcaine', 'Jamaican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (91, 'Japonaise', 'Japanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (92, 'Jordanienne', 'Jordanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (93, 'Kazakhstanaise', 'Kazakh');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (94, 'Kenyane', 'Kenyan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (95, 'Kirghize', 'Kyrgyzstani');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (96, 'Kiribatienne', 'Kiribati');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (97, 'Kittitienne', 'Kittitian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (98, 'Koweïtienne', 'Kuwaiti');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (99, 'Laotienne', 'Laotian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (100, 'Lesothane', 'Lesothane');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (101, 'Lettone', 'Latvian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (102, 'Libanaise', 'Lebanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (103, 'Libérienne', 'Liberian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (104, 'Libyenne', 'Libyan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (105, 'Liechtensteinoise', 'Leichtenstein');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (106, 'Lituanienne', 'Lithuanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (107, 'Luxembourgeoise', 'Luxembourg');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (108, 'Macanaise', 'Macanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (109, 'Macédonienne', 'Macedonian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (110, 'Malaisienne', 'Malaysian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (111, 'Malawienne', 'Malawian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (112, 'Maldivienne', 'Maldivian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (113, 'Malgache', 'Malagasy');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (114, 'Maliennes', 'Malian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (115, 'Maltaise', 'Maltese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (116, 'Marocaine', 'Moroccan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (117, 'Marshallaise', 'Marshallese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (118, 'Mauricienne', 'Mauritian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (119, 'Mauritanienne', 'Mauritanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (120, 'Mexicaine', 'Mexican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (121, 'Micronésienne', 'Mikronesian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (122, 'Moldave', 'Moldovan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (123, 'Monegasque', 'Monegasque');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (124, 'Mongole', 'Mongolian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (125, 'Monténégrine', 'Montenegrin');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (126, 'Mozambicaine', 'Mozambican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (127, 'Namibienne', 'Namibian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (128, 'Nauruane', 'Nauruan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (129, 'Néerlandaise', 'Dutch');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (130, 'Néo-zélandaise', 'New zealand');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (131, 'Népalaise', 'Nepalese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (132, 'Nicaraguayenne', 'Nicaraguan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (133, 'Nigériane', 'Nigerian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (134, 'Nigérienne', 'Nigerien');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (135, 'Niuéenne', 'Niuean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (136, 'Nord-coréenne', 'North korean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (137, 'Norvégienne', 'Norwegian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (138, 'Omanaise', 'Omani');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (139, 'Ougandaise', 'Ugandan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (140, 'Ouzbéke', 'Uzbek');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (141, 'Pakistanaise', 'Pakistani');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (142, 'Palaosienne', 'Palauan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (143, 'Palestinienne', 'Palestinian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (144, 'Panaméenne', 'Panamanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (145, 'Papouane-néo-guinéenne', 'Papua new guinean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (146, 'Paraguayenne', 'Paraguayan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (147, 'Péruvienne', 'Peruvian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (148, 'Philippine', 'Filipino');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (149, 'Pitcairnaise', 'Pitcairnese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (150, 'Polonaise', 'Polish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (151, 'Portugaise', 'Portugese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (152, 'Qatarienne', 'Qatari');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (153, 'Roumaine', 'Romanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (154, 'Russe', 'Russian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (155, 'Rwandaise', 'Rwandese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (156, 'Saint-lucienne', 'Saint lucian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (157, 'Saint-marinaise', 'Sanmarinese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (158, 'Saint-vincentaise', 'Vincentian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (159, 'Salomonaise', 'Solomon');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (160, 'Salvadorienne', 'Salvadorean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (161, 'Samoane', 'Samoan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (162, 'Santoméenne', 'Santomean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (163, 'Saoudienne', 'Saudi arabian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (164, 'Sénégalaise', 'Senegalese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (165, 'Serbe', 'Serbian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (166, 'Seychelloise', 'Seychellois');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (167, 'Sierra-léonaise', 'Sierra leonese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (168, 'Singapourienne', 'Singaporean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (169, 'Slovaque', 'Slovakian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (170, 'Slovène', 'Slovenian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (171, 'Somalienne', 'Somalian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (172, 'Soudanaise', 'Sudanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (173, 'Sri-lankaise', 'Sri lankan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (174, 'Sud-africaine', 'South african');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (175, 'Sud-coréenne', 'South korean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (176, 'Sud-soudanaise', 'South sudanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (177, 'Suédoise', 'Swedish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (178, 'Suisse', 'Swiss');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (179, 'Surinamaise', 'Surinamese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (180, 'Swazie', 'Swasi');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (181, 'Syrienne', 'Syrian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (182, 'Tadjike', 'Tajik');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (183, 'Taïwanaise', 'Taiwanese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (184, 'Tanzanienne', 'Tanzanian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (185, 'Tchadienne', 'Chadian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (186, 'Tchèque', 'Czech');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (187, 'Thaïlandaise', 'Thai');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (188, 'Togolaise', 'Togolese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (189, 'Tonguienne', 'Tongan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (190, 'Trinidadienne', 'Trinidadian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (191, 'Tunisienne', 'Tunisian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (192, 'Turkmène', 'Turkmen');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (193, 'Turque', 'Turkish');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (194, 'Tuvaluane', 'Tuvaluan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (195, 'Ukrainienne', 'Ukrainian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (196, 'Uruguayenne', 'Uruguayan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (197, 'Vanuatuane', 'Vanuatuan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (198, 'Vaticane', 'Vatican');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (199, 'Vénézuélienne', 'Venezuelan');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (200, 'Vietnamienne', 'Vietnamese');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (201, 'Yéménite', 'Yemeni');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (202, 'Zambienne', 'Zambian');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (203, 'Zimbabwéenne', 'Zimbabwean');
INSERT INTO data_nationality (id, label_fr, label_en) VALUES (204, 'Autre nationalité', 'Other nationality');