
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (1, '€', 'EUR', 'Euro', 1);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (2, '$', 'USD', 'United States dollar', 1);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (3, '¥', 'JPY', 'Japanese yen', 1);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (4, '£', 'GBP', 'British pound', 1);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (5, '$', 'CAD', 'Canadian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (6, '$', 'AUD', 'Australian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (7, '$', 'NZD', 'New Zealand dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (8, '؋', 'AFN', 'Afghan afghani', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (9, 'Lek', 'ALL', 'Albanian lek', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (10, 'د.ج', 'DZD', 'Algerian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (11, 'Kz ', 'AOA', 'Angolan kwanza', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (12, '$', 'ARS', 'Argentine peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (13, 'դր.', 'AMD', 'Armenian dram', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (14, 'ƒ', 'AWG', 'Aruban florin', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (15, 'ман', 'AZN', 'Azerbaijani manat', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (16, '$', 'BSD', 'Bahamian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (17, 'ب.د', 'BHD', 'Bahraini dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (18, '৳', 'BDT', 'Bangladeshi taka', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (19, '$', 'BBD', 'Barbadian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (20, 'p.', 'BYR', 'Belarusian ruble', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (21, 'BZ$', 'BZD', 'Belize dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (22, '$', 'BMD', 'Bermudian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (23, 'BTN', 'BTN', 'Bhutanese ngultrum', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (24, '$b', 'BOB', 'Bolivian boliviano', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (25, 'XBA', 'XBA', 'Bond Markets', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (26, 'KM', 'BAM', 'Bosnia and Herzegovina convert', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (27, 'P', 'BWP', 'Botswana pula', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (28, 'R$', 'BRL', 'Brazilian real', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (29, '$', 'BND', 'Brunei dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (30, 'лв', 'BGN', 'Bulgarian lev', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (31, 'Fr ', 'BIF', 'Burundian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (32, '៛', 'KHR', 'Cambodian riel', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (33, '$', 'CVE', 'Cape Verdean escudo', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (34, '$', 'KYD', 'Cayman Islands dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (35, 'Fr ', 'XAF', 'Central African CFA franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (36, 'Fr ', 'XPF', 'CFP franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (37, '$', 'CLP', 'Chilean peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (38, '元', 'CNY', 'Chinese renminbi yuan', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (39, 'XTS', 'XTS', 'Codes specif', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (40, '$', 'COP', 'Colombian peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (41, 'Fr ', 'KMF', 'Comorian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (42, 'Fr ', 'CDF', 'Congolese franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (43, '₡', 'CRC', 'Costa Rican colón', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (44, 'kn', 'HRK', 'Croatian kuna', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (45, '₱', 'CUP', 'Cuban peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (46, 'Kč', 'CZK', 'Czech koruna', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (47, 'kr', 'DKK', 'Danish krone', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (48, 'Fr ', 'DJF', 'Djiboutian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (49, 'RD$', 'DOP', 'Dominican peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (50, '$', 'XCD', 'East Caribbean dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (51, '£', 'EGP', 'Egyptian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (52, 'Nfk ', 'ERN', 'Eritrean nakfa', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (53, 'kr', 'EEK', 'Estonian kroon', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (54, 'ETB', 'ETB', 'Ethiopian birr', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (55, 'XBB', 'XBB', 'European Mon', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (56, 'XBD', 'XBD', 'European Uni', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (57, 'XBC', 'XBC', 'European Uni', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (58, '£', 'FKP', 'Falkland pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (59, '$', 'FJD', 'Fijian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (60, 'D ', 'GMD', 'Gambian dalasi', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (61, 'ლ', 'GEL', 'Georgian lari', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (62, '₵', 'GHS', 'Ghanaian cedi', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (63, '£', 'GIP', 'Gibraltar pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (64, 'Gold', 'XAU', 'Gold', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (65, 'Q', 'GTQ', 'Guatemalan quetzal', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (66, 'GWP', 'GWP', 'Guinea-Bissa', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (67, 'Fr ', 'GNF', 'Guinean franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (68, '$', 'GYD', 'Guyanese dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (69, 'G ', 'HTG', 'Haitian gourde', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (70, 'L', 'HNL', 'Honduran lempira', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (71, '元', 'HKD', 'Hong Kong dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (72, 'Ft', 'HUF', 'Hungarian forint', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (73, 'kr', 'ISK', 'Icelandic króna', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (74, '₨', 'INR', 'Indian rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (75, 'Rp', 'IDR', 'Indonesian rupiah', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (76, '﷼', 'IRR', 'Iranian rial', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (77, 'ع.د', 'IQD', 'Iraqi dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (78, '₪', 'ILS', 'Israeli new sheqel', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (79, 'J$', 'JMD', 'Jamaican dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (80, 'د.ا', 'JOD', 'Jordanian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (81, 'лв', 'KZT', 'Kazakhstani tenge', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (82, 'Sh ', 'KES', 'Kenyan shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (83, 'د.ك', 'KWD', 'Kuwaiti dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (84, 'лв', 'KGS', 'Kyrgyzstani som', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (85, '₭', 'LAK', 'Lao kip', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (86, 'Ls', 'LVL', 'Latvian lats', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (87, '£', 'LBP', 'Lebanese pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (88, 'L ', 'LSL', 'Lesotho loti', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (89, '$', 'LRD', 'Liberian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (90, 'ل.د', 'LYD', 'Libyan dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (91, 'Lt', 'LTL', 'Lithuanian litas', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (92, 'P ', 'MOP', 'Macanese pataca', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (93, 'ден', 'MKD', 'Macedonian denar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (94, 'MGA', 'MGA', 'Malagasy ariary', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (95, 'MK ', 'MWK', 'Malawian kwacha', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (96, 'RM', 'MYR', 'Malaysian ringgit', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (97, 'ރ.', 'MVR', 'Maldivian rufiyaa', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (98, 'UM ', 'MRO', 'Mauritanian ouguiya', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (99, '₨', 'MUR', 'Mauritian rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (100, '$', 'MXN', 'Mexican peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (101, 'MXV', 'MXV', 'Mexican Unid', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (102, 'L ', 'MDL', 'Moldovan leu', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (103, '₮', 'MNT', 'Mongolian tögrög', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (104, 'د.م.', 'MAD', 'Moroccan dirham', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (105, 'MT', 'MZN', 'Mozambican metical', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (106, 'BOV', 'BOV', 'Mvdol', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (107, 'K ', 'MMK', 'Myanmar kyat', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (108, '$', 'NAD', 'Namibian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (109, '₨', 'NPR', 'Nepalese rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (110, 'ƒ', 'ANG', 'Netherlands Antillean gulden', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (111, 'NT$', 'TWD', 'New Taiwan dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (112, 'C$', 'NIO', 'Nicaraguan córdoba', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (113, '₦', 'NGN', 'Nigerian naira', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (114, '₩', 'KPW', 'North Korean won', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (115, 'kr', 'NOK', 'Norwegian krone', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (116, '﷼', 'OMR', 'Omani rial', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (117, '₨', 'PKR', 'Pakistani rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (118, 'XPD', 'XPD', 'Palladium', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (119, 'B/.', 'PAB', 'Panamanian balboa', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (120, 'K ', 'PGK', 'Papua New Guinean kina', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (121, '₲', 'PYG', 'Paraguayan guaraní', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (122, 'S/.', 'PEN', 'Peruvian nuevo sol', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (123, '₱', 'PHP', 'Philippine peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (124, 'XPT', 'XPT', 'Platinum', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (125, 'zł', 'PLN', 'Polish Złoty', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (126, '﷼', 'QAR', 'Qatari riyal', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (127, 'lei', 'RON', 'Romanian leu', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (128, 'руб', 'RUB', 'Russian ruble', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (129, 'Fr ', 'RWF', 'Rwandan franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (130, '£', 'SHP', 'Saint Helenian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (131, '$', 'SVC', 'Salvadoran colón', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (132, 'T ', 'WST', 'Samoan tala', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (133, 'Db ', 'STD', 'São Tomé and Príncipe dobra', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (134, '﷼', 'SAR', 'Saudi riyal', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (135, 'XDR', 'XDR', 'SDR', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (136, 'Дин.', 'RSD', 'Serbian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (137, '₨', 'SCR', 'Seychellois rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (138, 'Le ', 'SLL', 'Sierra Leonean leone', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (139, 'XAG', 'XAG', 'Silver', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (140, '$', 'SGD', 'Singapore dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (141, 'Sk ', 'SKK', 'Slovak koruna', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (142, '$', 'SBD', 'Solomon Islands dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (143, 'S', 'SOS', 'Somali shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (144, 'R', 'ZAR', 'South African rand', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (145, '₩', 'KRW', 'South Korean won', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (146, '₨', 'LKR', 'Sri Lankan rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (147, '£ ', 'SDG', 'Sudanese pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (148, '$', 'SRD', 'Surinamese dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (149, 'L ', 'SZL', 'Swazi lilangeni', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (150, 'kr', 'SEK', 'Swedish krona', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (151, 'CHF', 'CHF', 'Swiss franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (152, '£', 'SYP', 'Syrian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (153, 'ЅМ', 'TJS', 'Tajikistani somoni', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (154, 'Sh ', 'TZS', 'Tanzanian shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (155, '฿', 'THB', 'Thai baht', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (156, 'XXX', 'XXX', 'The codes as', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (157, 'T$ ', 'TOP', 'Tongan paʻanga', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (158, 'TT$', 'TTD', 'Trinidad and Tobago dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (159, 'د.ت', 'TND', 'Tunisian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (160, 'YTL', 'TRY', 'Turkish new lira', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (161, 'm ', 'TMM', 'Turkmenistani manat', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (162, 'Sh ', 'UGX', 'Ugandan shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (163, 'XFU', 'XFU', 'UIC-Franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (164, '₴', 'UAH', 'Ukrainian hryvnia', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (165, 'COU', 'COU', 'Unidad de Va', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (166, 'CLF', 'CLF', 'Unidades de ', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (167, 'د.إ', 'AED', 'United Arab Emirates dirham', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (168, 'UYI', 'UYI', 'Uruguay Peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (169, '$', 'UYU', 'Uruguayan peso', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (170, '$', 'USN', 'US Dollar (Next Day)', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (171, '$', 'USS', 'US Dollar (Second Day)', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (172, 'лв', 'UZS', 'Uzbekistani som', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (173, 'Vt ', 'VUV', 'Vanuatu vatu', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (174, 'Bs', 'VEF', 'Venezuelan bolívar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (175, '₫', 'VND', 'Vietnamese Dong', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (176, 'Fr ', 'XOF', 'West African CFA franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (177, '€', 'CHE', 'WIR Euro', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (178, 'CHW', 'CHW', 'WIR Franc', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (179, '﷼', 'YER', 'Yemeni rial', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (180, 'ZK ', 'ZMK', 'Zambian kwacha', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (181, 'Z$', 'ZWD', 'Zimbabwean dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, name, published) VALUES (182, 'p.', 'BYN', 'Belarusian ruble', 0);

