
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (1, '€', 'EUR', '%n', 'Euro', 1);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (2, '$', 'USD', '%n', 'United States dollar', 1);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (3, '¥', 'JPY', '%n', 'Japanese yen', 1);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (4, '£', 'GBP', '%n', 'British pound', 1);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (5, '$', 'CAD', '%i', 'Canadian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (6, '$', 'AUD', '%i', 'Australian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (7, '$', 'NZD', '%i', 'New Zealand dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (8, '؋', 'AFN', '%i', 'Afghan afghani', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (9, 'Lek', 'ALL', '%i', 'Albanian lek', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (10, 'د.ج', 'DZD', '%i', 'Algerian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (11, 'Kz ', 'AOA', '%i', 'Angolan kwanza', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (12, '$', 'ARS', '%i', 'Argentine peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (13, 'դր.', 'AMD', '%i', 'Armenian dram', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (14, 'ƒ', 'AWG', '%i', 'Aruban florin', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (15, 'ман', 'AZN', '%i', 'Azerbaijani manat', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (16, '$', 'BSD', '%i', 'Bahamian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (17, 'ب.د', 'BHD', '%i', 'Bahraini dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (18, '৳', 'BDT', '%i', 'Bangladeshi taka', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (19, '$', 'BBD', '%i', 'Barbadian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (20, 'p.', 'BYR', '%i', 'Belarusian ruble', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (21, 'BZ$', 'BZD', '%i', 'Belize dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (22, '$', 'BMD', '%i', 'Bermudian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (23, 'BTN', 'BTN', '%i', 'Bhutanese ngultrum', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (24, '$b', 'BOB', '%i', 'Bolivian boliviano', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (25, 'XBA', 'XBA', '%i', 'Bond Markets', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (26, 'KM', 'BAM', '%i', 'Bosnia and Herzegovina convert', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (27, 'P', 'BWP', '%i', 'Botswana pula', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (28, 'R$', 'BRL', '%i', 'Brazilian real', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (29, '$', 'BND', '%i', 'Brunei dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (30, 'лв', 'BGN', '%i', 'Bulgarian lev', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (31, 'Fr ', 'BIF', '%i', 'Burundian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (32, '៛', 'KHR', '%i', 'Cambodian riel', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (33, '$', 'CVE', '%i', 'Cape Verdean escudo', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (34, '$', 'KYD', '%i', 'Cayman Islands dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (35, 'Fr ', 'XAF', '%i', 'Central African CFA franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (36, 'Fr ', 'XPF', '%i', 'CFP franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (37, '$', 'CLP', '%i', 'Chilean peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (38, '元', 'CNY', '%i', 'Chinese renminbi yuan', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (39, 'XTS', 'XTS', '%i', 'Codes specif', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (40, '$', 'COP', '%i', 'Colombian peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (41, 'Fr ', 'KMF', '%i', 'Comorian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (42, 'Fr ', 'CDF', '%i', 'Congolese franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (43, '₡', 'CRC', '%i', 'Costa Rican colón', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (44, 'kn', 'HRK', '%i', 'Croatian kuna', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (45, '₱', 'CUP', '%i', 'Cuban peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (46, 'Kč', 'CZK', '%i', 'Czech koruna', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (47, 'kr', 'DKK', '%i', 'Danish krone', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (48, 'Fr ', 'DJF', '%i', 'Djiboutian franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (49, 'RD$', 'DOP', '%i', 'Dominican peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (50, '$', 'XCD', '%i', 'East Caribbean dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (51, '£', 'EGP', '%i', 'Egyptian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (52, 'Nfk ', 'ERN', '%i', 'Eritrean nakfa', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (53, 'kr', 'EEK', '%i', 'Estonian kroon', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (54, 'ETB', 'ETB', '%i', 'Ethiopian birr', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (55, 'XBB', 'XBB', '%i', 'European Mon', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (56, 'XBD', 'XBD', '%i', 'European Uni', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (57, 'XBC', 'XBC', '%i', 'European Uni', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (58, '£', 'FKP', '%i', 'Falkland pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (59, '$', 'FJD', '%i', 'Fijian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (60, 'D ', 'GMD', '%i', 'Gambian dalasi', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (61, 'ლ', 'GEL', '%i', 'Georgian lari', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (62, '₵', 'GHS', '%i', 'Ghanaian cedi', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (63, '£', 'GIP', '%i', 'Gibraltar pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (64, 'Gold', 'XAU', '%i', 'Gold', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (65, 'Q', 'GTQ', '%i', 'Guatemalan quetzal', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (66, 'GWP', 'GWP', '%i', 'Guinea-Bissa', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (67, 'Fr ', 'GNF', '%i', 'Guinean franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (68, '$', 'GYD', '%i', 'Guyanese dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (69, 'G ', 'HTG', '%i', 'Haitian gourde', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (70, 'L', 'HNL', '%i', 'Honduran lempira', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (71, '元', 'HKD', '%i', 'Hong Kong dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (72, 'Ft', 'HUF', '%i', 'Hungarian forint', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (73, 'kr', 'ISK', '%i', 'Icelandic króna', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (74, '₨', 'INR', '%i', 'Indian rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (75, 'Rp', 'IDR', '%i', 'Indonesian rupiah', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (76, '﷼', 'IRR', '%i', 'Iranian rial', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (77, 'ع.د', 'IQD', '%i', 'Iraqi dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (78, '₪', 'ILS', '%n', 'Israeli new sheqel', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (79, 'J$', 'JMD', '%i', 'Jamaican dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (80, 'د.ا', 'JOD', '%i', 'Jordanian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (81, 'лв', 'KZT', '%i', 'Kazakhstani tenge', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (82, 'Sh ', 'KES', '%i', 'Kenyan shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (83, 'د.ك', 'KWD', '%i', 'Kuwaiti dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (84, 'лв', 'KGS', '%i', 'Kyrgyzstani som', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (85, '₭', 'LAK', '%i', 'Lao kip', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (86, 'Ls', 'LVL', '%i', 'Latvian lats', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (87, '£', 'LBP', '%i', 'Lebanese pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (88, 'L ', 'LSL', '%i', 'Lesotho loti', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (89, '$', 'LRD', '%i', 'Liberian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (90, 'ل.د', 'LYD', '%i', 'Libyan dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (91, 'Lt', 'LTL', '%i', 'Lithuanian litas', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (92, 'P ', 'MOP', '%i', 'Macanese pataca', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (93, 'ден', 'MKD', '%i', 'Macedonian denar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (94, 'MGA', 'MGA', '%i', 'Malagasy ariary', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (95, 'MK ', 'MWK', '%i', 'Malawian kwacha', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (96, 'RM', 'MYR', '%i', 'Malaysian ringgit', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (97, 'ރ.', 'MVR', '%i', 'Maldivian rufiyaa', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (98, 'UM ', 'MRO', '%i', 'Mauritanian ouguiya', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (99, '₨', 'MUR', '%i', 'Mauritian rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (100, '$', 'MXN', '%i', 'Mexican peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (101, 'MXV', 'MXV', '%i', 'Mexican Unid', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (102, 'L ', 'MDL', '%i', 'Moldovan leu', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (103, '₮', 'MNT', '%i', 'Mongolian tögrög', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (104, 'د.م.', 'MAD', '%i', 'Moroccan dirham', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (105, 'MT', 'MZN', '%i', 'Mozambican metical', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (106, 'BOV', 'BOV', '%i', 'Mvdol', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (107, 'K ', 'MMK', '%i', 'Myanmar kyat', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (108, '$', 'NAD', '%i', 'Namibian dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (109, '₨', 'NPR', '%i', 'Nepalese rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (110, 'ƒ', 'ANG', '%i', 'Netherlands Antillean gulden', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (111, 'NT$', 'TWD', '%i', 'New Taiwan dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (112, 'C$', 'NIO', '%i', 'Nicaraguan córdoba', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (113, '₦', 'NGN', '%i', 'Nigerian naira', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (114, '₩', 'KPW', '%i', 'North Korean won', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (115, 'kr', 'NOK', '%i', 'Norwegian krone', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (116, '﷼', 'OMR', '%i', 'Omani rial', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (117, '₨', 'PKR', '%i', 'Pakistani rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (118, 'XPD', 'XPD', '%i', 'Palladium', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (119, 'B/.', 'PAB', '%i', 'Panamanian balboa', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (120, 'K ', 'PGK', '%i', 'Papua New Guinean kina', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (121, '₲', 'PYG', '%i', 'Paraguayan guaraní', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (122, 'S/.', 'PEN', '%i', 'Peruvian nuevo sol', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (123, '₱', 'PHP', '%i', 'Philippine peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (124, 'XPT', 'XPT', '%i', 'Platinum', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (125, 'zł', 'PLN', '%i', 'Polish Złoty', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (126, '﷼', 'QAR', '%i', 'Qatari riyal', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (127, 'lei', 'RON', '%i', 'Romanian leu', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (128, 'руб', 'RUB', '%i', 'Russian ruble', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (129, 'Fr ', 'RWF', '%i', 'Rwandan franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (130, '£', 'SHP', '%i', 'Saint Helenian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (131, '$', 'SVC', '%i', 'Salvadoran colón', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (132, 'T ', 'WST', '%i', 'Samoan tala', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (133, 'Db ', 'STD', '%i', 'São Tomé and Príncipe dobra', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (134, '﷼', 'SAR', '%i', 'Saudi riyal', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (135, 'XDR', 'XDR', '%i', 'SDR', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (136, 'Дин.', 'RSD', '%i', 'Serbian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (137, '₨', 'SCR', '%i', 'Seychellois rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (138, 'Le ', 'SLL', '%i', 'Sierra Leonean leone', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (139, 'XAG', 'XAG', '%i', 'Silver', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (140, '$', 'SGD', '%i', 'Singapore dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (141, 'Sk ', 'SKK', '%i', 'Slovak koruna', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (142, '$', 'SBD', '%i', 'Solomon Islands dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (143, 'S', 'SOS', '%i', 'Somali shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (144, 'R', 'ZAR', '%i', 'South African rand', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (145, '₩', 'KRW', '%i', 'South Korean won', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (146, '₨', 'LKR', '%i', 'Sri Lankan rupee', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (147, '£ ', 'SDG', '%i', 'Sudanese pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (148, '$', 'SRD', '%i', 'Surinamese dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (149, 'L ', 'SZL', '%i', 'Swazi lilangeni', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (150, 'kr', 'SEK', '%i', 'Swedish krona', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (151, 'CHF', 'CHF', '%i', 'Swiss franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (152, '£', 'SYP', '%i', 'Syrian pound', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (153, 'ЅМ', 'TJS', '%i', 'Tajikistani somoni', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (154, 'Sh ', 'TZS', '%i', 'Tanzanian shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (155, '฿', 'THB', '%i', 'Thai baht', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (156, 'XXX', 'XXX', '%i', 'The codes as', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (157, 'T$ ', 'TOP', '%i', 'Tongan paʻanga', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (158, 'TT$', 'TTD', '%i', 'Trinidad and Tobago dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (159, 'د.ت', 'TND', '%i', 'Tunisian dinar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (160, 'YTL', 'TRY', '%i', 'Turkish new lira', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (161, 'm ', 'TMM', '%i', 'Turkmenistani manat', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (162, 'Sh ', 'UGX', '%i', 'Ugandan shilling', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (163, 'XFU', 'XFU', '%i', 'UIC-Franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (164, '₴', 'UAH', '%i', 'Ukrainian hryvnia', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (165, 'COU', 'COU', '%i', 'Unidad de Va', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (166, 'CLF', 'CLF', '%i', 'Unidades de ', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (167, 'د.إ', 'AED', '%i', 'United Arab Emirates dirham', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (168, 'UYI', 'UYI', '%i', 'Uruguay Peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (169, '$', 'UYU', '%i', 'Uruguayan peso', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (170, '$', 'USN', '%i', 'US Dollar (Next Day)', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (171, '$', 'USS', '%i', 'US Dollar (Second Day)', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (172, 'лв', 'UZS', '%i', 'Uzbekistani som', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (173, 'Vt ', 'VUV', '%i', 'Vanuatu vatu', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (174, 'Bs', 'VEF', '%i', 'Venezuelan bolívar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (175, '₫', 'VND', '%i', 'Vietnamese Dong', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (176, 'Fr ', 'XOF', '%i', 'West African CFA franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (177, '€', 'CHE', '%i', 'WIR Euro', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (178, 'CHW', 'CHW', '%i', 'WIR Franc', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (179, '﷼', 'YER', '%i', 'Yemeni rial', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (180, 'ZK ', 'ZMK', '%i', 'Zambian kwacha', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (181, 'Z$', 'ZWD', '%i', 'Zimbabwean dollar', 0);
INSERT INTO data_currency (id, symbol, iso3, format, name, published) VALUES (182, 'p.', 'BYN', '%i', 'Belarusian ruble', 0);

