favicon: 'gantry-media://custom/favicon.png'
css:
  -
    location: 'gantry-assets://custom/scss/custom.scss'
    inline: ''
    extra: {  }
    priority: '0'
    name: 'CUSTOM SCSS'
  -
    location: 'gantry-assets://custom/scss/global.scss'
    inline: ''
    extra: {  }
    priority: '0'
    name: Global
  -
    location: /modules/mod_falang/style/mod_falang_emundus.css
    inline: ''
    extra: {  }
    priority: '0'
    name: Falang
  -
    location: modules/mod_emundus_footer/css/mod_emundus_footer.css
    inline: ''
    extra: {  }
    priority: '0'
    name: Footer
  -
    location: 'https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined'
    inline: ''
    extra: '{  }'
    priority: '0'
    name: 'Material Icons'
