CREATE TABLE IF NOT EXISTS `#__miniorange_saml_customer_details` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`email` VARCHAR(255) NOT NULL,
`password` VARCHAR(255)  NOT NULL ,
`admin_phone` VARCHAR(255)  NOT NULL ,
`customer_key` VARCHAR(255)  NOT NULL ,
`customer_token` VARCHAR(255) NOT NULL,
`api_key` VARCHAR(255)  NOT NULL,
`licenseExpiry` TIMESTAMP NULL DEFAULT NULL,
`supportExpiry` TIMESTAMP NULL DEFAULT NULL,
`licensePlan` VARCHAR(56) NOT NULL,
`login_status` tinyint(1) DEFAULT FALSE,
`status` VARCHAR(255) NOT NULL,
`new_registration` BOOLEAN NOT NULL,
`sml_lk` VARCHAR(255) NOT NULL,
`in_cmp` VARCHAR(255) NOT NULL,
`email_count` int(11),
`enable_admin_login` BOOLEAN DEFAULT FALSE,
`enable_manager_login` BOOLEAN DEFAULT FALSE,
`enable_redirect` BOOLEAN DEFAULT FALSE,
`ignore_special_characters` BOOLEAN DEFAULT FALSE,
`enable_admin_redirect` BOOLEAN DEFAULT FALSE,
`user_login_for_other_domains` VARCHAR(255) DEFAULT 'BLOCK',
`sp_base_url` VARCHAR(255),
`sp_entity_id` VARCHAR(255),
`idp_link_page` VARCHAR(255),
`mo_idp_list_link_page` VARCHAR(255),
`mo_admin_idp_list_link_page` VARCHAR(255),
`organization_name` VARCHAR(100),
`organization_display_name` VARCHAR(100),
`organization_url` VARCHAR(100),
`tech_per_name` VARCHAR(100),
`tech_email_add` VARCHAR(100),
`support_per_name` VARCHAR(100),
`support_email_add` VARCHAR(100),
`trists` TEXT NOT NULL,
`usrlmt` int(11) NOT NULL,
`noSP` int(11) NOT NULL,
`enable_email` BOOLEAN DEFAULT TRUE,
`enable_admin_child_login` BOOLEAN DEFAULT FALSE,
`enable_manager_child_login` BOOLEAN DEFAULT FALSE,
`auto_send_email_time` TEXT,
`enable_do_not_auto_create_users` BOOLEAN DEFAULT FALSE,
`miniorange_fifteen_days_before_lexp` tinyint default 0,
`miniorange_five_days_before_lexp` tinyint default 0,
`miniorange_after_lexp` tinyint default 0,
`miniorange_after_five_days_lexp` tinyint default 0,
`miniorange_lexp_notification_sent` tinyint default 0,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__miniorange_saml_config` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`idp_entity_id` VARCHAR(255)  NOT NULL,
`single_signon_service_url` VARCHAR(255) DEFAULT NULL,
`binding` VARCHAR(255) DEFAULT NULL,
`single_logout_url` VARCHAR(1024) DEFAULT NULL,
`default_relay_state` VARCHAR(128),
`certificate` text DEFAULT NULL,
`username` VARCHAR(255) DEFAULT NULL,
`email` VARCHAR(255) DEFAULT NULL,
`name` VARCHAR(255) DEFAULT NULL,
`idp_name` VARCHAR(255) DEFAULT NULL,
`domain_mapping` VARCHAR(4096) DEFAULT NULL,
`public_certificate` VARCHAR(4096) DEFAULT NULL,
`private_certificate` VARCHAR(4096) DEFAULT NULL,
`mo_saml_country_code_text` VARCHAR(12) DEFAULT NULL,
`mo_saml_certificate_state_name` VARCHAR(32) DEFAULT NULL,
`mo_saml_certificate_company_name` VARCHAR(64) DEFAULT NULL,
`miniorange_saml_unit_name` VARCHAR(24) DEFAULT NULL,
`mo_saml_certificate_common_name` VARCHAR(24) DEFAULT NULL,
`mo_saml_select_digest_algo` VARCHAR(12) DEFAULT NULL,
`mo_saml_select_private_key_bit` INT(12) DEFAULT NULL,
`mo_saml_select_valid_days` INT(12) DEFAULT NULL,
`mo_saml_select_sign_algo` VARCHAR (256) DEFAULT NULL,
`auto_sync_enable`  VARCHAR(255) DEFAULT NULL,
`metadata_url`  VARCHAR(255) DEFAULT NULL,
`metadata_check_timestamp`  VARCHAR(255) DEFAULT NULL,
`mdata_sync_interval`  VARCHAR(255) DEFAULT NULL,
`user_profile_attributes` TEXT DEFAULT NULL,
`user_field_attributes` TEXT DEFAULT NULL,
`user_contact_attributes` TEXT DEFAULT NULL,
`user_cw_attributes` TEXT DEFAULT NULL,
`saml_request_sign` VARCHAR(10) DEFAULT NULL,
`name_id_format` VARCHAR(255) DEFAULT NULL,
`miniorange_saml_idp_slo_binding` VARCHAR(15) DEFAULT NULL,
`disable_update_existing_customer_attributes` BOOLEAN DEFAULT FALSE,
`AuthnContextClassRef` VARCHAR(255) DEFAULT 'PasswordProtectedTransport',
`first_name` VARCHAR (128),
`last_name` VARCHAR (128),
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__miniorange_saml_role_mapping` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`mapping_value_default` VARCHAR(255)  NULL,
`role_mapping_count` int(11) UNSIGNED  NULL,
`mapping_memberof_attribute` VARCHAR(255)  NULL,
`role_mapping_key_value` text NULL,
`enable_saml_role_mapping` int(11) UNSIGNED NULL,
`idp_id` int(11) NOT NULL,
`do_not_auto_create_users` int(11),
`disable_existing_users_role_update` BOOLEAN NOT NULL default 0,
`update_existing_users_role_without_removing_current` BOOLEAN NOT NULL default 0,
`enable_role_based_redirection` BOOLEAN NOT NULL default 0,
`role_based_redirect_key_value`  text NOT NULL,
`grp` VARCHAR(255) NULL,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

INSERT IGNORE INTO `#__miniorange_saml_customer_details`(`id`,`login_status`,`organization_name`,`organization_display_name`,`organization_url`,`tech_per_name`,`tech_email_add`,`support_per_name`,`support_email_add`) values (1,1,'miniOrange','miniOrange','http://miniorange.com','miniOrange','joomlasupport@xecurify.com','miniOrange','joomlasupport@xecurify.com') ;

