ordering:
  dossiers: ''
  evaluations: ''
  rapport-activite:
    comptes-utilisateurs: ''
    dossiers-candidature: ''
    email-history: ''
  administration:
    programmes:
      declarer-un-nouveau-programme: ''
    liste-des-programmes-par-annee:
      ajouter-une-annee-pour-un-programme: ''
    periode-depot-dossier:
      creer-campagne: ''
    utilisateurs: ''
    parametrage-des-profils-utilisateurs: ''
    parametrage-des-statuts: ''
    paiements: ''
    acces-admin: ''
  paramettres:
    emails-parametrage:
      declencheurs: ''
    configuration-des-courriers: ''
    types-documents: ''
    setup-tags: ''
    groupes: ''
items:
  dossiers:
    id: 542
  evaluations:
    id: 145
  rapport-activite:
    id: 144
    dropdown_dir: center
    dropdown_hide: '0'
    width: auto
  rapport-activite/comptes-utilisateurs:
    id: 1559
  rapport-activite/dossiers-candidature:
    id: 1558
  rapport-activite/email-history:
    id: 16
  administration:
    id: 591
    dropdown_dir: center
    dropdown_hide: '0'
    width: auto
  administration/programmes:
    id: 1173
  administration/programmes/declarer-un-nouveau-programme:
    id: 1171
  administration/liste-des-programmes-par-annee:
    id: 1161
  administration/liste-des-programmes-par-annee/ajouter-une-annee-pour-un-programme:
    id: 1172
  administration/periode-depot-dossier:
    id: 1159
  administration/periode-depot-dossier/creer-campagne:
    id: 1274
  administration/utilisateurs:
    id: 592
  administration/parametrage-des-profils-utilisateurs:
    id: 1288
  administration/parametrage-des-statuts:
    id: 2715
  administration/paiements:
    id: 2714
  administration/acces-admin:
    id: 2800
  paramettres:
    id: 2729
    dropdown_dir: center
    dropdown_hide: '0'
    width: auto
  paramettres/emails-parametrage:
    id: 1164
  paramettres/emails-parametrage/declencheurs:
    id: 1533
  paramettres/configuration-des-courriers:
    id: 1163
  paramettres/types-documents:
    id: 1322
  paramettres/setup-tags:
    id: 2650
  paramettres/groupes:
    id: 1169
