<?php

/**
 * @package     Joomla
 * @subpackage  com_emundus
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\Language\Text;
use Joomla\CMS\Factory;

$app = Factory::getApplication();
$user = $app->getIdentity();

if (empty($user->id)) {
	$app->redirect(JRoute::_('index.php?option=com_users&view=login', false));
}

## MENU ##
Text::script('COM_EMUNDUS_ONBOARD_SIDEMENUHELP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDMENU');
Text::script('COM_EMUNDUS_ONBOARD_PREVIEW');
Text::script('COM_EMUNDUS_ONBOARD_ELEMENTTOOLTIPS');
Text::script('COM_EMUNDUS_ONBOARD_FORM_PAGE');
Text::script('COM_EMUNDUS_ONBOARD_SUBMIT_PAGE');
Text::script('COM_EMUNDUS_ONBOARD_NO_ELEMENTS_TIPS');
Text::script('COM_EMUNDUS_ONBOARD_FORM');
Text::script('COM_EMUNDUS_ONBOARD_ADD');
Text::script('COM_EMUNDUS_ONBOARD_SAVE');
Text::script('COM_EMUNDUS_ONBOARD_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_ADD_NEW_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BUILD_YOUR_FORM');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDMENU_ACTION');
Text::script('COM_EMUNDUS_ADD_SECTION');
Text::script('COM_EMUNDUS_FILES_PAGE');
## END ##

## FIELDS ##
Text::script('COM_EMUNDUS_ONBOARD_FIELD_NAME');
Text::script('COM_EMUNDUS_ONBOARD_FIELD_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_FIELD_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
Text::script('COM_EMUNDUS_ONBOARD_DELETE_TEMPLATE_DOC');
Text::script('COM_EMUNDUS_ONBOARD_MODEL_DELETED');
Text::script('COM_EMUNDUS_ONBOARD_MODEL_DELETED_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_CANNOT_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_CANNOT_DELETE_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_ADDDOC_DESCRIPTION');
## END ##

## CAMPAIGNS ##
Text::script('COM_EMUNDUS_ONBOARD_FORM_AFFECTCAMPAIGNS');
Text::script('COM_EMUNDUS_ONBOARD_FORM_CAMPAIGNSEMPTY');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_BACK_WITHOUT_ASSOCIATION');
## END ##

## DOCUMENTS ##
Text::script('COM_EMUNDUS_ONBOARD_CREATE_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_EDIT_DOCUMENT');
Text::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
Text::script('COM_EMUNDUS_ONBOARD_OK');
Text::script('COM_EMUNDUS_ONBOARD_LASTNAME');
Text::script('COM_EMUNDUS_ONBOARD_ADDCAMP_DESCRIPTION');
Text::script('COM_EMUNDUS_ONBOARD_MAXPERUSER');
Text::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED');
Text::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_MAXPERUSER_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_FILETYPE_ACCEPTED_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
Text::script('COM_EMUNDUS_ONBOARD_PDF_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_PICTURES_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_OFFICE_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_EXCEL_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_AUDIO');
Text::script('COM_EMUNDUS_ONBOARD_TEMPLATE_DOC');
Text::script('COM_EMUNDUS_ONBOARD_ADDDOC_DESCRIPTION');
## END ##

## GLOBAL ##
Text::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
Text::script('COM_EMUNDUS_ONBOARD_ADD_CONTINUER');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_CANT_REVERT');
Text::script('COM_EMUNDUS_ONBOARD_ACTIONS');
Text::script('COM_EMUNDUS_ONBOARD_OK');
Text::script('COM_EMUNDUS_ONBOARD_CANCEL');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_DELETE');
Text::script('COM_EMUNDUS_ONBOARD_ACTIONS_SETTINGS');
Text::script('COM_EMUNDUS_ONBOARD_ACTIONS_REQUIRED');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_UNPUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_ACTION_PUBLISH');
Text::script('COM_EMUNDUS_ONBOARD_UPDATEFORMTIP');
Text::script('COM_EMUNDUS_ONBOARD_UPDATEFORMTIP1');
Text::script('COM_EMUNDUS_ONBOARD_UPDATEFORMTIP2');
Text::script('COM_EMUNDUS_ONBOARD_TIP');
## END ##

## BUILDER ##
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATASAVED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INFORMATIONS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATESUCESS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_HELPTEXT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_OPTIONS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SIZE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDTYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDTEXT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDPHONE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_WIDTH');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_HEIGHT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDMENU');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGROUP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDITEM');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EDITGROUP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_GROUPORDERING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGROUP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_GROUPDELETED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_MENUORDERING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EDITMENU');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CREATEDELEMENT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CREATEDELEMENTSUCCES');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEELEMENT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ELEMENTDELETED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_MAXLENGTH');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_PLACEHOLDER_HELP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_MENUDELETED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEMENU');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEMENUWARNING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGROUPWARNING');
Text::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR_CAMPAIGN_EDIT');
Text::script('COM_EMUNDUS_ONBOARD_FORM_CHOOSE_EXISTING_MODEL_PAGE');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
Text::script('COM_EMUNDUS_ONBOARD_SAVE_AS_TEMPLATE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ORDERSUCESS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ORDERFAILED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATEFAILED');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CREATEDELEMENT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CREATEDELEMENTSUCCES');
Text::script('COM_EMUNDUS_ONBOARD_SEND_FORM');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_MAXLENGTH');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_USE_ADVANCED_EDITOR');
Text::script('COM_EMUNDUS_ONBOARD_MODIFY');
Text::script('COM_EMUNDUS_ONBOARD_REPEAT_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_REPEAT_GROUP_MESSAGE');
Text::script('COM_EMUNDUS_ONBOARD_REPEAT_GROUP_DISABLE');
Text::script('COM_EMUNDUS_ONBOARD_REPEAT_GROUP_MESSAGE_DISABLE');
Text::script('COM_EMUNDUS_ONBOARD_TIP_DATABASEJOIN');
Text::script('COM_EMUNDUS_ONBOARD_TIP_DATABASEJOIN_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_REPEATED_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_DUPLICATE');
Text::script('COM_EMUNDUS_ONBOARD_DUPLICATE_ELEMENT');
Text::script('COM_EMUNDUS_ONBOARD_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_REQUIRED_FORM');
Text::script('COM_EMUNDUS_ONBOARD_REQUIRED_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_TARGET');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_TRANSLATE_IN');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ADD_OPTIONS');
Text::script('COM_EMUNDUS_ONBOARD_TESTING_FORM');
Text::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_CREATE_FILE');
Text::script('COM_EMUNDUS_ONBOARD_CONTINUE_FILE');
Text::script('COM_EMUNDUS_ONBOARD_FILE_EXIST_BEFORE_TESTING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_CALENDAR');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATE_FORMATTING');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATE_FORMAT_BIRTHDAY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATE_FORMAT_YEAR');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_NO_DEFAULT_VALUE');
Text::script('COM_EMUNDUS_ONBOARD_ELEMENT_OPTIONS');
Text::script('COM_EMUNDUS_ONBOARD_SAVING_AT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EXIT_FORMBUILDER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SUBMITTION_PAGE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EDIT_NAME');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_EDIT_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_HIDE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_HIDE_MESSAGE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_ORDER_BY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_HIDDEN_GROUP');
Text::script('COM_EMUNDUS_ONBOARD_PERSONAL_INFORMATIONS');
Text::script('COM_EMUNDUS_ONBOARD_ADRESSE');
Text::script('COM_EMUNDUS_ONBOARD_WORK_EXPERIENCE');
Text::script('COM_EMUNDUS_ONBOARD_EMPTY_SECTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_FIELD_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_FIELD');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_BIRTHDAY');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_CHECKBOX');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_DROPDOWN');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_RADIOBUTTON');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_TEXTAREA');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_DISPLAY');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_FILE');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_YESNO');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_LASTNAME');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_FIRSTNAME');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_YESNO');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_PHONE_NUMBER');
Text::script('COM_EMUNDUS_FORM_BUILDER_PUBLISH');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTIONS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_SECTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_EMPTY_SECTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_EMPTY_DOCUMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_SAVE');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_UNPUBLISH');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_REQUIRED');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_PARAMETERS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_GENERAL');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_HIDDEN');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_CONTENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_LABEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVED_AT');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_DOCUMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_REQUIRED_DOCUMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_OPTIONAL_DOCUMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_MODEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_NAME');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_DESCRIPTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_NBMAX');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_TYPES');
Text::script('COM_EMUNDUS_FORM_BUILDER_EVERY_DOCUMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_ALLOWED_TYPES');
Text::script('COM_EMUNDUS_FORM_BUILDER_MAX_DOCUMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_REQUIRED_DOCUMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_OPTIONAL_DOCUMENTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_EVERY_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_ELEMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_ELEMENT_CONFIRM');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_SECTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_SECTION_CONFIRM');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_DOCUMENT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_DOCUMENT_CONFIRM');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_OPTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_NEW_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_DESCRIPTION');
Text::script('COM_EMUNDUS_FORM_BUILDER_SUBMISSION_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DUPLICATE_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_PAGE_CONFIRMATION');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_PAGE_CONFIRMATION_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_PAGE_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_PAGE_ERROR_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_PAGE_PROPERTIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_PAGE_LABEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_PAGE_INTRO');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_ERROR_LABEL_EMPTY');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_ERROR_LABEL_EXISTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_PAGE_PROPERTIES_ADD');
Text::script('COM_EMUNDUS_FORM_BUILDER_MAX_SECTION_TITLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_MAX_SECTION_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_PROPERTIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_ADVANCED');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_PROPERTIES_SELECT_TYPE');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_IMG');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_AUDIO');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_VIDEO');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_PDF');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_TABLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS_OTHER');
Text::script('COM_EMUNDUS_FORM_BUILDER_FORMATS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_FORMAT');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_FORMAT_DESC');
Text::script('COM_EMUNDUS_FORM_BUILDER_CANCEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_CONTACT_ADD_FORMAT');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_PAGE_INTRO_ADD');
Text::script('COM_EMUNDUS_FORM_BUILDER_ADD_PAGE_TITLE_ADD');
Text::script('COM_EMUNDUS_FORM_BUILDER_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_ERROR_UPDATE_GROUP_PARAMS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ERROR_UPDATE_PARAMS');
Text::script('COM_EMUNDUS_FORM_BUILDER_ERROR_SAVE_TRANSLATION');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_NEW_PAGE');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_NEW_PAGE_INTRO');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_NEW_PAGE_FROM_MODEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_PAGE_CREATE_SAVE');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_MANDATORY');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_NOT_MANDATORY');
Text::script('COM_EMUNDUS_FORM_BUILDER_UPDATE_ELEMENTS_ORDER_FAILED');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_PLEASE_FILL_TYPE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_PLEASE_FILL_FORMAT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE_TEXT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE_PHONE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE_EMAIL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE_LINK');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELD_TYPE_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_DISPLAY_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_WYSIWIG');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_LIMIT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_SHOWMAX_LIMIT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_LIMIT_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_LIMIT_TYPE_CHARACTERS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TEXTAREA_LIMIT_TYPE_WORDS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CHECKBOX_OPTIONS_PER_ROW');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_RADIOBUTTON_OPTIONS_PER_ROW');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DROPDOWN_ADVANCED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_ADVANCED');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_LIST_METHOD');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_LIST_METHOD_YEARS_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_LIST_METHOD_SINCE_YEAR');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_LIST_METHOD_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_LIST_METHOD_NUMBER_TIP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_YEARS_FUTURE_PAST');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_YEARS_FUTURE_PAST_TIP');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT_D_MONTH_YYYY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT_D_MONTH_YYYY_2');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT_MONTH_D_YYYY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_BIRTHDAY_FORMAT_D_M');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_YESNO_DEFAULT_VALUE');
Text::script('COM_EMUNDUS_ONBOARD_WANTED_FILE_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CALC_VALUE');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_DATABASEJOIN');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_DISPLAY_TYPE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_DISPLAY_TYPE_DROPDOWN');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_DISPLAY_TYPE_RADIO');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_DISPLAY_TYPE_AUTOCOMPLETE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_SHOW_PLEASE_SELECT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_WHERE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_WHERE_AJAX');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_TABLE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_VALUE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_LABEL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_DATABASEJOIN_LABEL_CONCAT');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_CALENDAR');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CALENDAR_DEFAULT_TODAY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CALENDAR_FIRST_DAY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CALENDAR_SUNDAY');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_CALENDAR_MONDAY');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTION_PROPERTIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTION_LABEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_SECTION_PROPERTIES_SAVE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SECTIONS_INTRO');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SECTIONS_OUTRO');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SECTIONS_REPEAT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SECTIONS_REPEAT_MIN');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_SECTIONS_REPEAT_MAX');
Text::script('COM_EMUNDUS_FORM_BUILDER_NEW_VALUE');
Text::script('COM_EMUNDUS_FORM_BUILDER_EXISTING_VALUE');
Text::script('COM_EMUNDUS_FORM_BUILDER_MULTIPLE_FORMS_IMPACTED');
Text::script('COM_EMUNDUS_FORM_BUILDER_MULTIPLE_FORMS_IMPACTED_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETED_ELEMENT_TITLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETED_ELEMENT_TEXT');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_PAGE_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_GET_PAGE_MODELS_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL_INPUT');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL_INPUT_NOT_FILLED');
Text::script('COM_EMUNDUS_FORM_BUILDER_UNSAVE_MODEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_MODEL_FAILURE');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL_FAILURE');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL_TITLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DELETE_MODEL_TITLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_MODEL_PROPERTIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_MODEL_PROPERTIES_INTRO');
Text::script('COM_EMUNDUS_FORM_BUILDER_MODEL_INPUT_LABEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_MODEL_WITH_SAME_TITLE_EXISTS');
Text::script('COM_EMUNDUS_FORM_BUILDER_MODEL_MUST_HAVE_TITLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_EMPTY_PAGE_MODELS');
Text::script('COM_EMUNDUS_FORM_BUILDER_UPDATE_ORDER_PAGE_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_CREATE_SECTION_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_REQUEST_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_FAILED_TO_LOAD_FORM');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_MODEL_TITLE');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_GIVE_MODEL');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_MODEL_ADD');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_MODEL_EDIT');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_CURRENT_MODEL');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_DOWNLOAD_SAMPLE');
Text::script('COM_EMUNDUS_FORM_BUILDER_DOCUMENT_SAMPLE_WRONG_FORMAT');
Text::script('COM_EMUNDUS_FORMBUILDER_DOCUMENTS_MODEL_FILE_UPLOADED');
Text::script('COM_EMUNDUS_FORM_BUILDER_NEW_STRUCTURE');
Text::script('COM_EMUNDUS_FORM_BUILDER_INITIAL_STRUCTURE');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_GEOLOCATION');
Text::script('COM_EMUNDUS_FORM_BUILDER_GEOLOC_DEFAULT_LNG');
Text::script('COM_EMUNDUS_FORM_BUILDER_GEOLOC_DEFAULT_LAT');
Text::script('COM_EMUNDUS_FORM_BUILDER_GEOLOC_DEFAULT_ZOOM');
Text::script('COM_EMUNDUS_FORM_BUILDER_GEOLOC_GET_LOCATION');
Text::script('COM_EMUNDUS_FORM_BUILDER_SAVE_AS_MODEL_SUCCESS');
Text::script('COM_EMUNDUS_ONBOARD_SECTIONS_PERSONAL_DETAILS');
Text::script('COM_EMUNDUS_ONBOARD_SECTIONS_ADRESS');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_PHONE_NUMBER_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_PANEL_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_CURRENCY_DESC');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_DATABASEJOIN_DESC');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_ISO');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_MIN');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_MAX');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_THOUSAND_SEPARATOR');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_THOUSAND_SEPARATOR_BLANK_SPACE');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_THOUSAND_SEPARATOR_COMMA');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_THOUSAND_SEPARATOR_DOT');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_DECIMAL_SEPARATOR');
Text::script('COM_EMUNDUS_FORM_BUILDER_CURRENCY_CURRENCIES_DECIMAL_NUMBERS');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_DISPLAY_DESC');
Text::script('COM_EMUNDUS_FORM_BUILDER_ELEMENT_PROPERTIES_ADVANCED_FORMAT');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_TYPE_NONE');
Text::script('COM_EMUNDUS_ONBOARD_PARAMS_ADD_REPEATABLE');
## END ##

## TUTORIAL ##
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_CAMPAIGN');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORM');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORMBUILDER');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_DOCUMENTS');
Text::script('COM_EMUNDUS_ONBOARD_TUTORIAL_PROGRAM');
## END ##

### INPUT MASK
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INPUT_MASK_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INPUT_MASK_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INPUT_MASK_HINT');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INPUT_MASK_PREVIEW_TITLE');
### END

Text::script('COM_EMUNDUS_ONBOARD_BUILDER_INPUT_MASK');

# PAST/FUTUR YEARS
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_FUTURE_YEARS');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_YEAR_RANGE');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_TIP_YEARS_FUTURE');

# IMAGE RESOLUTION
Text::script('COM_EMUNDUS_ONBOARD_IMAGE_WIDTH');
Text::script('COM_EMUNDUS_ONBOARD_IMAGE_HEIGHT');
Text::script('COM_EMUNDUS_ONBOARD_IMAGE_RESOLUTION_TOOLTIPS');
Text::script('COM_EMUNDUS_ONBOARD_MIN_RESOLUTION_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_MAX_RESOLUTION_PLACEHOLDER');
Text::script('COM_EMUNDUS_ONBOARD_ERROR_RESOLUTION');
Text::script('COM_EMUNDUS_ONBOARD_ERROR_RESOLUTION_NEGATIVE');
Text::script('COM_EMUNDUS_ONBOARD_ERROR_RESOLUTION_TOO_SMALL');
Text::script('COM_EMUNDUS_ONBOARD_ERROR_RESOLUTION_NOT_NUMBER');
Text::script('COM_EMUNDUS_ONBOARD_IMAGE_DIMENSION_TITLE');
Text::script('COM_EMUNDUS_ONBOARD_TYPE_PANEL');
Text::script('COM_EMUNDUS_ONBOARD_BUILDER_PHONENUMBER_DEFAULT_COUNTRY');

Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_TYPE');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_TYPE_INFORMATION');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_TYPE_WARNING');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_TYPE_ERROR');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_ACCORDION');
Text::script('COM_EMUNDUS_FORM_BUILDER_PANEL_ACCORDION_TITLE');

$vue = 'em-formBuilder-vue';
if ($this->eval != 0) {
	$vue = 'em-evaluationBuilder-vue';
}
$lang         = $app->getLanguage();
$short_lang   = substr($lang->getTag(), 0, 2);
$current_lang = $lang->getTag();
$languages    = JLanguageHelper::getLanguages();
if (count($languages) > 1) {
	$many_languages = '1';
	require_once(JPATH_ROOT . '/components/com_emundus/models/translations.php');
	$m_translations = new EmundusModelTranslations();
	$default_lang   = $m_translations->getDefaultLanguage()->lang_code;
}
else {
	$many_languages = '0';
	$default_lang   = $current_lang;
}

$coordinator_access = EmundusHelperAccess::asCoordinatorAccessLevel($user->id);
$sysadmin_access = EmundusHelperAccess::isAdministrator($user->id);
$component = $app->input->get('evaluation') ? 'evaluationbuilder' : 'formbuilder';

require_once(JPATH_ROOT . '/components/com_emundus/helpers/cache.php');
$hash = EmundusHelperCache::getCurrentGitHash();
$mode = $app->input->get('mode', '');

$settings_menu_alias = '';
$menus = $app->getMenu();
$items = $menus->getItems('component', 'com_emundus');
foreach ($items as $item) {
	if ($item->query['view'] == 'settings') {
		$settings_menu_alias = $item->alias;
		break;
	}
}

JHTML::script('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js');
?>

<div id="em-component-vue"
     component="<?= $component ?>"
     prid="<?= JFactory::getApplication()->input->get('prid') ?>"
     index="<?= JFactory::getApplication()->input->get('index') ?>"
     cid="<?= JFactory::getApplication()->input->get('cid') ?>"
     shortLang="<?= $short_lang ?>" currentLanguage="<?= $current_lang ?>"
     manyLanguages="<?= $many_languages ?>"
     defaultLang="<?= $default_lang ?>"
     coordinatorAccess="<?= $coordinator_access ?>"
     sysadminAccess="<?= $sysadmin_access ?>"
     settingsMenuAlias="<?= $settings_menu_alias ?>"
	<?php if (!empty($mode)) : ?>
        mode="<?= $mode ?>"
	<?php endif; ?>
></div>

<script src="media/com_emundus_vue/app_emundus.js?<?php echo $hash ?>"></script>
