<?php

defined('_JEXEC') or die;

/**
 * This file is automatically generated. It contains a secret key used for encrypting data by the component. Please do
 * not remove, edit or manually replace this file. It will render your existing encrypted data unreadable forever.
 */
 
define('LOGINGUARD_FOF_ENCRYPT_SERVICE_SECRETKEY', 'CaxUA20eBufbhOXKNaVaiLRCRXZPWPu9Xn0Lis7HMGsOqX81vlw58cJOwD8JMMhe');
