<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus_onboard
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_PLACEHOLDER_OUTPUT_STATUS");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_PLACEHOLDER_SUPPLEMENTARY_INFORMATION");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_LABEL");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_INPUT_STATUS");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_OUTPUT_STATUS");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_START_DATE");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_END_DATE");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_SUPPLEMENTARY_INFORMATION");
JText::script("COM_EMUNDUS_WORKFLOW_STEP_MODAL_STEP_TITLE_STEP_COLOR");

JText::script("COM_EMUNDUS_WORKFLOW_COMMON_ADD_BUTTON_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_SAVE_BUTTON_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_EXIT_BUTTON_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_REMOVE_BUTTON_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_CONFIGURE_BUTTON_TITLE");

JText::script("COM_EMUNDUS_WORKFLOW_COMMON_SWEET_ALERT_CONGRATULATION_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_SWEET_ALERT_CONGRATULATION_MESSAGE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_SWEET_ALERT_ERROR_TITLE");
JText::script("COM_EMUNDUS_WORKFLOW_COMMON_SWEET_ALERT_ERROR_MESSAGE");

JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_PLACEHOLDER_LABEL");
JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_PLACEHOLDER_PROFILE");
JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_PLACEHOLDER_SUPPLEMENTARY_INFORMATION");
JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_TITLE_LABEL");
JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_TITLE_PROFILE");
JText::script("COM_EMUNDUS_WORKFLOW_ELEMENT_ESPACE_MODAL_TITLE_SUPPLEMENTARY_INFORMATION");
//JText::script("");
//JText::script("");

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');
$document = JFactory::getDocument();
$document->addScript('media/com_emundus_workflow/chunk-vendors.js');
$document->addStyleSheet('media/com_emundus_workflow/app.css');

?>

<div id="add-item"></div>

<script src="media/com_emundus_workflow/app.js"></script>
