<?php
/**
 * @package     Joomla
 * @subpackage  com_emundus_onboard
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access to this file
defined('_JEXEC') or die('Restricted Access');
$document = JFactory::getDocument();
$document->addScript('media/com_emundus_onboard/chunk-vendors_onboard.js');
$document->addStyleSheet('media/com_emundus_onboard/app_onboard.css');

require_once (JPATH_COMPONENT.DS.'helpers'.DS.'access.php');

## GLOBAL ##
JText::script('COM_EMUNDUS_ONBOARD_ADD_RETOUR');
JText::script('COM_EMUNDUS_ONBOARD_ADD_CONTINUER');
JText::script('COM_EMUNDUS_ONBOARD_DEPOTDEDOSSIER');
JText::script('COM_EMUNDUS_ONBOARD_ADD_QUITTER');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADVANCED_SETTINGS');
JText::script('COM_EMUNDUS_ONBOARD_MODIFY');
JText::script('COM_EMUNDUS_ONBOARD_OK');
JText::script('COM_EMUNDUS_ONBOARD_CANCEL');
## END ##

## FORMS ##
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_PROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_ADDCAMP_CHOOSEPROG');
JText::script('COM_EMUNDUS_ONBOARD_ADDPROGRAM');
JText::script('COM_EMUNDUS_ONBOARD_PROGNAME');
JText::script('COM_EMUNDUS_ONBOARD_PROGCODE');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_NAMECATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_EDITOR_UNDO');
JText::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
JText::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CODE');
JText::script('COM_EMUNDUS_ONBOARD_PROG_REQUIRED_CATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_REQUIRED_FIELDS_INDICATE');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_RESUME');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CODE');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CATEGORY');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADDUSER');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
JText::script('COM_EMUNDUS_ONBOARD_FIRSTNAME');
JText::script('COM_EMUNDUS_ONBOARD_FIRSTNAME_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_LASTNAME');
JText::script('COM_EMUNDUS_ONBOARD_LASTNAME_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_PSEUDO_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_ROLE');
JText::script('COM_EMUNDUS_ONBOARD_ROLE_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_NAME');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_INTRO');
JText::script('COM_EMUNDUS_ONBOARD_FORM_REQUIRED_NAME');
JText::script('COM_EMUNDUS_ONBOARD_TRANSLATE_ENGLISH');
JText::script('COM_EMUNDUS_ONBOARD_SAVE_AS_TEMPLATE');
## END ##

## FILTERS ##
JText::script('COM_EMUNDUS_ONBOARD_FILTER_PUBLISH');
JText::script('COM_EMUNDUS_ONBOARD_SELECT_ALL');
## END ##

## DESCRIPTION ##
JText::script('COM_EMUNDUS_ONBOARD_USERSDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_VISIBILITYDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_EMAILSDESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_MANUAL_DESCRIPTION');
JText::script('COM_EMUNDUS_ONBOARD_EVALUATIONGRIDDESCRIPTION');
## END ##

## TRIGGERS ##
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_ADDTRIGGER');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_AFFECTTRIGGERS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERMODEL_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERSTATUS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGERTARGET_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGER_CHOOSE_USERS');
JText::script('COM_EMUNDUS_ONBOARD_TRIGGER_USERS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_EMAIL_PREVIEWMODEL');
JText::script('COM_EMUNDUS_ONBOARD_THE_CANDIDATE');
JText::script('COM_EMUNDUS_ONBOARD_MANUAL');
JText::script('COM_EMUNDUS_ONBOARD_CHANGED_ACTION_STATUS');
JText::script('COM_EMUNDUS_ONBOARD_CANDIDATE_ACTION');
JText::script('COM_EMUNDUS_ONBOARD_MANAGER_ACTION');
## END ##

## USERS ##
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_AFFECTUSERS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATORS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATORS');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_ADMINISTRATOR');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_EVALUATOR');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_USERSEMPTY');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_CANDIDATES');
JText::script('COM_EMUNDUS_ONBOARD_PROGRAM_DEFINED_USERS');
JText::script('COM_EMUNDUS_ONBOARD_SEARCH_USERS');
## END ##

## VISIBILITY ##
JText::script('COM_EMUNDUS_ONBOARD_VISIBILITY_ENABLE');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_FORM');
## END ##


## EVALUATION ##
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN');
JText::script('COM_EMUNDUS_ONBOARD_CHOOSE_CAMPAIGN_WARNING');
JText::script('COM_EMUNDUS_ONBOARD_NO_AFFECTED_FORM');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGROUP');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDGRID');
JText::script('COM_EMUNDUS_ONBOARD_GRIDMODEL');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGROUP');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEGROUPWARNING');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_GROUPDELETED');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEELEMENT');
JText::script('COM_EMUNDUS_ONBOARD_CANT_REVERT');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ELEMENTDELETED');
JText::script('COM_EMUNDUS_ONBOARD_ACTION_DELETE');
JText::script('COM_EMUNDUS_ONBOARD_ACTIONS_SETTINGS');
JText::script('COM_EMUNDUS_ONBOARD_ACTIONS_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_ACTION_UNPUBLISH');
JText::script('COM_EMUNDUS_ONBOARD_ACTION_PUBLISH');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ORDERFAILED');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ORDERSUCESS');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATEFAILED');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATESUCESS');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATING');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_UPDATE');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DELETEELEMENT');
JText::script('COM_EMUNDUS_ONBOARD_CANT_REVERT');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDITEM');
## END ##

## CRITERIA ##
JText::script('COM_EMUNDUS_ONBOARD_TYPE_FIELD');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_BIRTHDAY');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_CHECKBOX');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_DROPDOWN');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_RADIOBUTTON');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_TEXTAREA');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_NAME');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_TYPE');
JText::script('COM_EMUNDUS_ONBOARD_FIELD_REQUIRED');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_ADDITEM');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_HELPTEXT');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_PLACEHOLDER');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_SIZE');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_MAXLENGTH');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDTYPE');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDTEXT');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_FIELDPHONE');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_EMAIL');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_NUMBER');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_PLACEHOLDER_HELP');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_OPTIONS');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_WIDTH');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_HEIGHT');
JText::script('COM_EMUNDUS_ONBOARD_TYPE_COMMENT');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_USE_ADVANCED_EDITOR');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_DISPLAY_MAXLENGTH');
JText::script('COM_EMUNDUS_ONBOARD_BUILDER_CREATEDGROUPSUCCES');
## END ##

## TUTORIAL ##
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_CAMPAIGN');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORM');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_FORMBUILDER');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_DOCUMENTS');
JText::script('COM_EMUNDUS_ONBOARD_TUTORIAL_PROGRAM');
## END ##

$lang = JFactory::getLanguage();
$actualLanguage = substr($lang->getTag(), 0, 2);

$user = JFactory::getUser();
$coordinator_access = EmundusonboardHelperAccess::isCoordinator($user->id);
?>

<div id="em-addProgramAdvancedSettings-vue" prog="<?= $this->id ;?>" actualLanguage="<?= $actualLanguage ?>" coordinatorAccess="<?= $coordinator_access ?>"></div>

<script src="media/com_emundus_onboard/app_onboard.js"></script>
