/* update "jos_emundus_uploads */
/* replace 'user_id'.plugin = 'user' (from 'fields') and its params */
update jos_fabrik_elements as jfe
set jfe.plugin = 'user',
    jfe.params = '{"my_table_data":"name","update_on_edit":"2","update_on_copy":"0","user_use_social_plugin_profile":"0","user_noselectionlabel":"","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top","labelindetails":"1","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","validations":[]}'
where jfe.name like '%user_id%' and jfe.plugin like '%field%' and jfe.group_id = 117;

/* resolve conflict : merge remote-tracking */
UPDATE `jos_securitycheckpro_storage` SET storage_value = REPLACE(storage_value, '"session_protection_active":"1"', '"session_protection_active":"0"') WHERE storage_key like "pro_plugin";
