INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('PROGRAMME_LOGO', 'fr-FR', 'Logo du programme', 'Logo du programme', MD5('Logo du programme'), MD5('Logo du programme'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('PROGRAMME_LOGO', 'en-GB', 'Programme logo', 'Programme logo', MD5('Programme logo'), MD5('Programme logo'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('PROGRAMME', 'en-GB', 'Programme', 'Programme', MD5('Programme'), MD5('Programme'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('PROGRAMME', 'fr-FR', 'Programme', 'Programme', MD5('Programme'), MD5('Programme'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('IS_LIMITED', 'fr-FR', 'Limiter les candidatures', 'Limiter les candidatures', MD5('Limiter les candidatures'), MD5('Limiter les candidatures'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('IS_LIMITED', 'en-GB', 'Limiting applications', 'Limiting applications', MD5('Limiting applications'), MD5('Limiting applications'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_DOCUMENTS', 'en-GB', 'Copy attachments', 'Copy attachments', MD5('Copy attachments'), MD5('Copy attachments'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_DELETE_FROM_FILE', 'en-GB', 'Delete the original file after copying', 'Delete the original file after copying', MD5('Delete the original file after copying'), MD5('Delete the original file after copying'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_MOVE_HIKASHOP', 'en-GB', 'Move Hikashop commands', 'Move Hikashop commands', MD5('Move Hikashop commands'), MD5('Move Hikashop commands'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_TAG', 'en-GB', 'Copy the tags', 'Copy the tags', MD5('Copy the tags'), MD5('Copy the tags'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LIMIT', 'fr-FR', 'Limite', 'Limite', MD5('Limite'), MD5('Limite'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LIMIT', 'en-GB', 'Limit', 'Limit', MD5('Limit'), MD5('Limit'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LIMIT_STATUS', 'en-GB', 'Status to limit', 'Status to limit', MD5('Status to limit'), MD5('Status to limit'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LIMIT_STATUS', 'fr-FR', 'Statut à limiter', 'Statut à limiter', MD5('Statut à limiter'), MD5('Statut à limiter'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('TIMEZONE', 'fr-FR', 'Timezone : ', 'Timezone : ', MD5('Timezone : '), MD5('Timezone : '), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('TIMEZONE', 'en-GB', 'Timezone: ', 'Timezone: ', MD5('Timezone: '), MD5('Timezone: '), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LOGOUT', 'en-GB', 'Logout', 'Logout', MD5('Logout'), MD5('Logout'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('FORMATION', 'fr-FR', 'Formation', 'Formation', MD5('Formation'), MD5('Formation'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('FORMATION', 'en-GB', 'Training', 'Training', MD5('Training'), MD5('Training'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('CREATE_NEW_MENU', 'fr-FR', 'Créer un nouveau menu', 'Créer un nouveau menu', MD5('Créer un nouveau menu'), MD5('Créer un nouveau menu'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('CREATE_NEW_MENU', 'en-GB', 'Create new menu', 'Create new menu', MD5('Create new menu'), MD5('Create new menu'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('VIDEO_MAX_LENGTH', 'fr-FR', 'Taille max de la vidéo', 'Taille max de la vidéo', MD5('Taille max de la vidéo'), MD5('Taille max de la vidéo'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('VIDEO_MAX_LENGTH', 'en-GB', 'Vidéo Max Lenght', 'Vidéo Max Lenght', MD5('Vidéo Max Lenght'), MD5('Vidéo Max Lenght'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MIN_PDF', 'fr-FR', 'Nombre minimum de page dans le pdf', 'Nombre minimum de page dans le pdf', MD5('Nombre minimum de page dans le pdf'), MD5('Nombre minimum de page dans le pdf'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MIN_PDF', 'en-GB', 'Minimum page number in pdf', 'Minimum page number in pdf', MD5('Minimum page number in pdf'), MD5('Minimum page number in pdf'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MAX_PDF', 'fr-FR', 'Nombre maximum de page dans le pdf', 'Nombre maximum de page dans le pdf', MD5('Nombre maximum de page dans le pdf'), MD5('Nombre maximum de page dans le pdf'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MAX_PDF', 'en-GB', 'Maximum page number in pdf', 'Maximum page number in pdf', MD5('Maximum page number in pdf'), MD5('Maximum page number in pdf'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

---------

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('TABLE_SETUP_LETTERS_INTRO', 'fr-FR', 'Générer automatiquement des courriers personnalisés pour vos candidats. Vous pouvez y inclure des champs dynamiques appelés «balises», qui seront remplacés par les données renseignées par vos candidats.', 'Générer automatiquement des courriers personnalisés pour vos candidats. Vous pouvez y inclure des champs dynamiques appelés «balises», qui seront remplacés par les données renseignées par vos candidats.', MD5('Générer automatiquement des courriers personnalisés pour vos candidats. Vous pouvez y inclure des champs dynamiques appelés «balises», qui seront remplacés par les données renseignées par vos candidats.'), MD5('Générer automatiquement des courriers personnalisés pour vos candidats. Vous pouvez y inclure des champs dynamiques appelés «balises», qui seront remplacés par les données renseignées par vos candidats.'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('TABLE_SETUP_LETTERS_INTRO', 'en-GB', 'Automatically generate personalised mailings for your candidates. You can include dynamic fields called "tags", which will be replaced by the data filled in by your candidates.', 'Automatically generate personalised mailings for your candidates. You can include dynamic fields called "tags", which will be replaced by the data filled in by your candidates.', MD5('Automatically generate personalised mailings for your candidates. You can include dynamic fields called "tags", which will be replaced by the data filled in by your candidates.'), MD5('Automatically generate personalised mailings for your candidates. You can include dynamic fields called "tags", which will be replaced by the data filled in by your candidates.'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CAMPAIGNS', 'fr-FR', 'Pour quelle(s) campagnes(s) souhaitez-vous que ce courrier soit généré ?', 'Pour quelle(s) campagnes(s) souhaitez-vous que ce courrier soit généré ?', MD5('Pour quelle(s) campagnes(s) souhaitez-vous que ce courrier soit généré ?'), MD5('Pour quelle(s) campagnes(s) souhaitez-vous que ce courrier soit généré ?'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CAMPAIGNS', 'en-GB', 'For which campaign(s) would you like this mail to be generated?', 'For which campaign(s) would you like this mail to be generated?', MD5('For which campaign(s) would you like this mail to be generated?'), MD5('For which campaign(s) would you like this mail to be generated?'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_PROGRAMS', 'fr-FR', 'Pour quel(s) programme(s) souhaitez-vous que ce courrier soit généré ?', 'Pour quel(s) programme(s) souhaitez-vous que ce courrier soit généré ?', MD5('Pour quel(s) programme(s) souhaitez-vous que ce courrier soit généré ?'), MD5('Pour quel(s) programme(s) souhaitez-vous que ce courrier soit généré ?'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_PROGRAMS', 'en-GB', 'For which programme(s) do you want this mail to be generated?', 'For which programme(s) do you want this mail to be generated?', MD5('For which programme(s) do you want this mail to be generated?'), MD5('For which programme(s) do you want this mail to be generated?'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_STATUS', 'fr-FR', 'Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?', 'Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?', MD5('Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?'), MD5('Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_STATUS', 'en-GB', 'For which status(es) do you want this mail to be generated?', 'For which status(es) do you want this mail to be generated?', MD5('For which status(es) do you want this mail to be generated?'), MD5('For which status(es) do you want this mail to be generated?'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_INTRO', 'fr-FR', "<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Besoin d'aide ?</a></p>
", "<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Besoin d'aide ?</a></p>
", MD5("<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Besoin d'aide ?</a></p>
"), MD5("<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Besoin d'aide ?</a></p>
"), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_INTRO', 'en-GB', "<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Need help ?</a></p>
", "<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Need help ?</a></p>
", MD5("<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Need help ?</a></p>
"), MD5("<p style='text-align: right;'><a href='https://emundus.atlassian.net/wiki/external/1668448315/YmRiNGUyMjI3ODQ4NDZjZWIxNDRiMWQ4ZDIwODQwNGI?atlOrigin=eyJpIjoiMjZiMTk4ZWVhMDk3NDExN2JhOWNkYTk4YjFiZmQ2MzgiLCJwIjoiYyJ9' target='_blank' rel='noopener noreferrer'>Need help ?</a></p>
"), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_DOCUMENT_TYPE_HINT', 'fr-FR', "Votre modèle de courrier doit être rattaché à un type de document pour être visible dans vos dossiers. Si vous ne trouvez pas votre type de document, vous pouvez en <a href='administration-site/types-documents/form/34'>créer un nouveau</a>.", "Votre modèle de courrier doit être rattaché à un type de document pour être visible dans vos dossiers. Si vous ne trouvez pas votre type de document, vous pouvez en <a href='administration-site/types-documents/form/34'>créer un nouveau</a>.", MD5("Votre modèle de courrier doit être rattaché à un type de document pour être visible dans vos dossiers. Si vous ne trouvez pas votre type de document, vous pouvez en <a href='administration-site/types-documents/form/34'>créer un nouveau</a>."), MD5("Votre modèle de courrier doit être rattaché à un type de document pour être visible dans vos dossiers. Si vous ne trouvez pas votre type de document, vous pouvez en <a href='administration-site/types-documents/form/34'>créer un nouveau</a>."), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_DOCUMENT_TYPE_HINT', 'en-GB', "Your mail template must be attached to a document type to be visible in your folders. If you cannot find your document type, you can <a href='administration-site/types-documents/form/34'>create a new one</a>.", "Your mail template must be attached to a document type to be visible in your folders. If you cannot find your document type, you can <a href='administration-site/types-documents/form/34'>create a new one</a>.", MD5("Your mail template must be attached to a document type to be visible in your folders. If you cannot find your document type, you can <a href='administration-site/types-documents/form/34'>create a new one</a>."), MD5("Your mail template must be attached to a document type to be visible in your folders. If you cannot find your document type, you can <a href='administration-site/types-documents/form/34'>create a new one</a>."), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CAMPAIGNS_HINT', 'fr-FR', 'Ce courrier ne sera disponible que lorsque le statut du candidat fera partie de ceux que vous avez sélectionné.', 'Ce courrier ne sera disponible que lorsque le statut du candidat fera partie de ceux que vous avez sélectionné.', MD5('Ce courrier ne sera disponible que lorsque le statut du candidat fera partie de ceux que vous avez sélectionné.'), MD5('Ce courrier ne sera disponible que lorsque le statut du candidat fera partie de ceux que vous avez sélectionné.'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CAMPAIGNS_HINT', 'en-GB', "This mail will only be available when the applicant's status is one of those you have selected.", "This mail will only be available when the applicant's status is one of those you have selected.", MD5("This mail will only be available when the applicant's status is one of those you have selected."), MD5("This mail will only be available when the applicant's status is one of those you have selected."), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_PROGRAMS_HINT', 'fr-FR', 'Ce courrier ne sera disponible que pour les candidats inscrits dans le(s) programme(s) sélectionné(s).', 'Ce courrier ne sera disponible que pour les candidats inscrits dans le(s) programme(s) sélectionné(s).', MD5('Ce courrier ne sera disponible que pour les candidats inscrits dans le(s) programme(s) sélectionné(s).'), MD5('Ce courrier ne sera disponible que pour les candidats inscrits dans le(s) programme(s) sélectionné(s).'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_PROGRAMS_HINT', 'en-GB', 'This mail will only be available to applicants registered in the selected programme(s).', 'This mail will only be available to applicants registered in the selected programme(s).', MD5('This mail will only be available to applicants registered in the selected programme(s).'), MD5('This mail will only be available to applicants registered in the selected programme(s).'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_STATUS_HINT', 'fr-FR', 'Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?', 'Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?', MD5('Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?'), MD5('Pour quel(s) statut(s) souhaitez-vous que ce courrier soit généré ?'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_STATUS_HINT', 'en-GB', 'For which status(es) do you want this mail to be generated?', 'For which status(es) do you want this mail to be generated?', MD5('For which status(es) do you want this mail to be generated?'), MD5('For which status(es) do you want this mail to be generated?'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CREATE_A_TEMPLATE_FROM_HINT', 'fr-FR', 'Créez votre modèle directement depuis votre plateforme ou depuis un logiciel externe.', 'Créez votre modèle directement depuis votre plateforme ou depuis un logiciel externe.', MD5('Créez votre modèle directement depuis votre plateforme ou depuis un logiciel externe.'), MD5('Créez votre modèle directement depuis votre plateforme ou depuis un logiciel externe.'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_CREATE_A_TEMPLATE_FROM_HINT', 'en-GB', 'Create your template directly from your platform or from external software.', 'Create your template directly from your platform or from external software.', MD5('Create your template directly from your platform or from external software.'), MD5('Create your template directly from your platform or from external software.'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_179', 'fr-FR', 'Contenu du courrier', 'Contenu du courrier', MD5('Contenu du courrier'), MD5('Contenu du courrier'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_179', 'en-GB', 'Content of the letter', 'Content of the letter', MD5('Content of the letter'), MD5('Content of the letter'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_179_INTRO', 'fr-FR', "<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>", "<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>", MD5("<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>"), MD5("<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>"), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_179_INTRO', 'en-GB', "<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>", "<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>", MD5("<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>"), MD5("<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>"), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LETTER_TYPE', 'fr-FR', 'Type de lettre', 'Type de lettre', MD5('Type de lettre'), MD5('Type de lettre'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LETTER_TYPE', 'en-GB', 'Type of letter', 'Type of letter', MD5('Type of letter'), MD5('Type of letter'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LETTER_EXPORT_TO_PDF', 'fr-FR', 'Générer en pdf', 'Générer en pdf', MD5('Générer en pdf'), MD5('Générer en pdf'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('LETTER_EXPORT_TO_PDF', 'en-GB', 'Generate in pdf', 'Generate in pdf', MD5('Generate in pdf'), MD5('Generate in pdf'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_185', 'fr-FR', 'Contenu du courrier', 'Contenu du courrier', MD5('Contenu du courrier'), MD5('Contenu du courrier'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_185', 'en-GB', 'Content of the letter', 'Content of the letter', MD5('Content of the letter'), MD5('Content of the letter'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_185_INTRO', 'fr-FR', "<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>", "<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>", MD5("<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>"), MD5("<p>Pour rendre ce courrier dynamique, insérer des <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>balises</a> dans sa construction afin d’ajouter des informations personnalisées pour chaque candidat. Par exemple, la balise <em>$APPLICANT_NAME</em> sera remplacée par le nom de votre candidat. Bonjour <em>$APPLICANT_NAME</em> deviendra Bonjour Julien.</p>"), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SETUP_LETTERS_GROUP_185_INTRO', 'en-GB', "<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>", "<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>", MD5("<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>"), MD5("<p>To make this mail dynamic, insert <a href='component/emundus/?view=export_select_columns&format=html&layout=all_programs' target='_blank' rel='noopener noreferrer'>tags</a> in its construction in order to add personalised information for each candidate. For example, the tag <em>$APPLICANT_NAME</em> will be replaced by the name of your candidate. Hello <em>$APPLICANT_NAME</em> will become Hello Julien.</p>"), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
