INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_DOCUMENTS', 'fr-FR', 'Copier les documents', 'Copier les documents', MD5('Copier les documents'), MD5('Copier les documents'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_DELETE_FROM_FILE', 'fr-FR', 'Supprimer le dossier d''origine après la copie', 'Supprimer le dossier d''origine après la copie', MD5('Supprimer le dossier d''origine après la copie'), MD5('Supprimer le dossier d''origine après la copie'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_APPLICATION_MOVE_HIKASHOP', 'fr-FR', 'Déplacer les commandes Hikashop', 'Déplacer les commandes Hikashop', MD5('Déplacer les commandes Hikashop'), MD5('Déplacer les commandes Hikashop'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('EMUNDUS_COPY_TAG', 'fr-FR', 'Copier les étiquettes', 'Copier les étiquettes', MD5('Copier les étiquettes'), MD5('Copier les étiquettes'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MAX_PAGES_PDF', 'fr-FR', 'Nombre de page(s) maximum pour le pdf', 'Nombre de page(s) maximum pour le pdf', MD5('Nombre de page(s) maximum pour le pdf'), MD5('Nombre de page(s) maximum pour le pdf'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COM_EMUNDUS_ATTACHMENTS_MAX_PAGES_PDF', 'en-GB', 'Maximum number of page(s) for the pdf', 'Maximum number of page(s) for the pdf', MD5('Maximum number of page(s) for the pdf'), MD5('Maximum number of page(s) for the pdf'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SEND_CREDENTIALS_BY_EMAIL', 'fr-FR', 'Envoyer un email d''information lors de l''importation', 'Envoyer un email d''information lors de l''importation', MD5('Envoyer un email d''information lors de l''importation'), MD5('Envoyer un email d''information lors de l''importation'), 'fr-FR.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('SEND_CREDENTIALS_BY_EMAIL', 'en-GB', 'Send an information email when importing', 'Send an information email when importing', MD5('Send an information email when importing'), MD5('Send an information email when importing'), 'en-GB.override.ini', 'override', null, 'fabrik_elements', 'label', 1, 62, '2022-06-30 08:28:03', null, null);
