ALTER TABLE jos_emundus_campaign_candidature ADD copy_users_assoc INT NULL;
ALTER TABLE jos_emundus_campaign_candidature ADD copy_groups_assoc INT NULL;

INSERT INTO jos_fabrik_elements (name, group_id, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params) VALUES ('copy_groups_assoc', 254, 'radiobutton', 'COPY_GROUPS_ASSOC', 0, '0000-00-00 00:00:00', '2023-03-10 09:22:09', 62, 'sysadmin', '0000-00-00 00:00:00', 0, 0, 0, '', 0, 0, 25, 0, '', 1, 1, 0, 0, 0, 1, 0, 0, '{"sub_options":{"sub_values":["0","1"],"sub_labels":["JNO","JYES"]},"options_per_row":"4","btnGroup":"0","allow_frontend_addtoradio":"0","rad-allowadd-onlylabel":"0","rad-savenewadditions":"0","dropdown_populate":"","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","validations":[]}');
INSERT INTO jos_fabrik_elements (name, group_id, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params) VALUES ('copy_groups_assoc', 175, 'radiobutton', 'COPY_GROUPS_ASSOC', 0, '0000-00-00 00:00:00', '2023-03-10 09:22:09', 62, 'sysadmin', '0000-00-00 00:00:00', 0, 0, 0, '', 0, 0, 25, 0, '', 1, 0, 0, 0, 0, 1, 0, 9546, '{"sub_options":{"sub_values":["0","1"],"sub_labels":["JNO","JYES"]},"options_per_row":"4","btnGroup":"0","allow_frontend_addtoradio":"0","rad-allowadd-onlylabel":"0","rad-savenewadditions":"0","dropdown_populate":"","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","validations":[]}');


INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COPY_USER_ASSOC', 'fr-FR', 'Copier les utilisateurs associés', 'Copier les utilisateurs associés', MD5('Copier les utilisateurs associés'), MD5('Copier les utilisateurs associés'), 'fr-FR.override.ini', 'override', @email_cc, 'fabrik_elements', 'label', 1, 62, '2022-06-05 12:52:22', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COPY_USER_ASSOC', 'en-GB', 'Copy associated users', 'Copy associated users', MD5('Copy associated users'), MD5('Copy associated users'), 'en-GB.override.ini', 'override', @email_cc, 'fabrik_elements', 'label', 1, 62, '2022-06-05 12:52:22', null, null);

INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COPY_GROUPS_ASSOC', 'fr-FR', 'Copier les groupes associés', 'Copier les groupes associés', MD5('Copier les groupes associés'), MD5('Copier les groupes associés'), 'fr-FR.override.ini', 'override', @email_cc, 'fabrik_elements', 'label', 1, 62, '2022-06-05 12:52:22', null, null);
INSERT INTO jos_emundus_setup_languages (tag, lang_code, override, original_text, original_md5, override_md5, location, type, reference_id, reference_table, reference_field, published, created_by, created_date, modified_by, modified_date)
VALUES ('COPY_GROUPS_ASSOC', 'en-GB', 'Copy associated groups', 'Copy associated groups', MD5('Copy associated groups'), MD5('Copy associated groups'), 'en-GB.override.ini', 'override', @email_cc, 'fabrik_elements', 'label', 1, 62, '2022-06-05 12:52:22', null, null);