UPDATE jos_content
SET note = ""
WHERE alias IN ('bienvenue-dans-votre-espace-de-gestion','creeons-une-campagne-ensemble','premiers-pas','premiers-pas-2','configuration-de-la-campagne','felicitations','creation-de-votre-formulaire','modification-des-elements');

INSERT INTO jos_content (id, asset_id, title, alias, introtext, `fulltext`, state, catid, created, created_by, created_by_alias, modified, modified_by, checked_out, checked_out_time, publish_up, publish_down, images, urls, attribs, version, ordering, metakey, metadesc, access, hits, metadata, featured, language, xreference, note)
VALUES (1008, 0, 'Paramétrer son programme', 'parametrer-son-programme', '<p>Dans les paramètres du programme de nombreuses possibilités vous sont offertes afin de gérez aux mieux vos futures campagnes.</p>
<p>Dans la première section de ces paramètres vous pouvez gérez toute votre équipe en ajoutant des gestionnaires et des évaluateurs propre à ce programme.</p>', '', 1, 102, '2020-08-27 13:54:25', 62, '', '2020-08-27 14:17:05', 62, 0, '2020-08-27 13:54:25', '2020-08-27 13:54:25', '2099-06-25 18:11:14', '{}', '{}', '{"article_layout":"","show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}', 5, 2, '', '', 1, 0, '{}', 0, '*', '', '');
INSERT INTO jos_content (id, asset_id, title, alias, introtext, `fulltext`, state, catid, created, created_by, created_by_alias, modified, modified_by, checked_out, checked_out_time, publish_up, publish_down, images, urls, attribs, version, ordering, metakey, metadesc, access, hits, metadata, featured, language, xreference, note)
VALUES (1009, 0, 'Evaluations', 'evaluations', '<p>Les évaluations permettent de sélectionner les dossiers en suivant des critères précis que vous définissez.</p>
<p>Pour définir ces critères vous devez créer une grille d''évaluation. Afin de vous aider dans votre tâche on vous propose un modèle que vous pouvez modifiez à votre guise.</p>', '', 1, 102, '2020-08-27 14:12:13', 62, '', '2020-08-27 14:17:58', 62, 0, '2020-08-27 13:54:25', '2020-08-27 14:12:13', '2099-06-25 18:11:14', '{}', '{}', '{"article_layout":"","show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}', 3, 1, '', '', 1, 0, '{}', 0, '*', '', '');
INSERT INTO jos_content (id, asset_id, title, alias, introtext, `fulltext`, state, catid, created, created_by, created_by_alias, modified, modified_by, checked_out, checked_out_time, publish_up, publish_down, images, urls, attribs, version, ordering, metakey, metadesc, access, hits, metadata, featured, language, xreference, note)
VALUES (1010, 0, 'Emails', 'emails', '<p>Une dernière étape afin d''améliorer votre processus de sélection : l''envoi automatique d’e-mails.</p>
<p>Par exemple définissez un e-mail qui sera envoyé aux évaluateurs lorsque le candidat a envoyé son dossier.</p>
<p><img src="/images/emundus/saas_tutorial/email_trigger.gif" alt="" width="577" height="325" /></p>', '', 1, 102, '2020-08-27 14:31:26', 62, '', '2020-08-27 14:38:16', 62, 0, '2020-08-27 13:54:25', '2020-08-27 14:31:26', '2099-06-25 18:11:14', '{}', '{}', '{"article_layout":"","show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}', 2, 0, '', '', 1, 0, '{}', 0, '*', '', '');

INSERT INTO jos_modules (asset_id, title, note, content, ordering, position, checked_out, checked_out_time, publish_up, publish_down, published, module, access, showtitle, params, client_id, language)
VALUES (321, 'mod_emundus_tutorial_saas_program', '', '', 1, 'content-tutorial-a', 0, '2020-06-08 15:26:47', '2020-06-08 15:26:47', '2099-06-08 15:26:47', 1, 'mod_emundus_tutorial', 7, 0, '{"artids":"1008,1009,1010","user_param":"first_program","layout":"_:saas","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*');
SET @module_id := LAST_INSERT_ID();

INSERT INTO jos_modules_menu (moduleid,menuid)
VALUES (@module_id,0);

INSERT INTO jos_fields (asset_id, context, group_id, title, name, label, default_value, type, note, description, state, required, checked_out, checked_out_time, ordering, params, fieldparams, language, created_time, created_user_id, modified_time, modified_by, access)
VALUES (0, 'com_content.article', 0, 'params', 'params', 'params', '', 'text', '', '', 1, 0, 0, '2020-06-08 15:26:47', 0, '{"hint":"","class":"","label_class":"","show_on":"","render_class":"","showlabel":"1","label_render_class":"","display":"2","layout":"","display_readonly":"2"}', '{"filter":"","maxlength":""}', '*', '2020-08-21 10:36:53', 62, '2020-08-21 10:36:53', 0, 1);
SET @field_id := LAST_INSERT_ID();

INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1002', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1000', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1007', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_NEXT","view":"form","layout":"formbuilder"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1006', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"form","layout":"formbuilder"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1005', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"form","layout":"addnextcampaign"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1004', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CREATE_FORM","link":"index.php?option=com_emundus_onboard&view=form&layout=add&cid=","view":"form","layout":"addnextcampaign"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1003', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CREATE_CAMPAIGN","link":"configuration-campaigns?view=campaign&layout=add"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1001', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"campaign","layout":"add"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1008', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"program","layout":"advancedsettings"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1009', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"program","layout":"advancedsettings"}');
INSERT INTO jos_fields_values (field_id, item_id, value) VALUES (@field_id, '1010', '{"confirm_text":"MOD_EMUNDUS_TUTORIAL_CONTINUE","view":"program","layout":"advancedsettings"}');

ALTER TABLE jos_emundus_setup_groups ADD IF NOT EXISTS parent_id int(11) NULL AFTER anonymize;
