CREATE TABLE `jos_emundus_plugin_events`
(
    `id`              int(11)      NOT NULL AUTO_INCREMENT,
    `label`           varchar(100) NOT NULL,
    `published`       tinyint(1)   NOT NULL DEFAULT 1,
    `category`        varchar(50)           DEFAULT NULL,
    `description`     text                  DEFAULT NULL,
    `label_translate` varchar(100)          DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `jos_emundus_plugin_events_label_uindex` (`label`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

INSERT INTO `jos_emundus_plugin_events` (`label`, `published`, `category`, `description`, `label_translate`)
VALUES ('onBeforeStatusChange', 1, 'Status', NULL, NULL),
       ('onAfterStatusChange', 1, 'Status', NULL, NULL),
       ('onBeforePublishChange', 1, 'File', NULL, NULL),
       ('onAfterPublishChange', 1, 'File', NULL, NULL),
       ('onBeforeDeleteFile', 1, 'File', NULL, NULL),
       ('onAfterDeleteFile', 1, 'File', NULL, NULL),
       ('onBeforeSaveEmundusUser', 1, 'User', NULL, NULL),
       ('onAfterSaveEmundusUser', 1, 'User', NULL, NULL),
       ('onBeforeAddUserToGroup', 1, 'User', NULL, NULL),
       ( 'onAfterAddUserToGroup', 1, 'User', NULL, NULL),
       ( 'onBeforeAddUserProfile', 1, 'User', NULL, NULL),
       ( 'onAfterAddUserProfile', 1, 'User', NULL, NULL),
       ( 'onBeforeCampaignCandidature', 1, 'File', NULL, NULL),
       ( 'onAfterCampaignCandidature', 1, 'File', NULL, NULL),
       ( 'onBeforeCampaignCreate', 1, 'Camapign', NULL, NULL),
       ( 'onAfterCampaignCreate', 1, 'Camapign', NULL, NULL),
       ( 'onBeforeCampaignChange', 1, 'Camapign', NULL, NULL),
       ( 'onAfterCampaignChange', 1, 'Camapign', NULL, NULL),
       ( 'onBeforeCampaignDelete', 1, 'Camapign', NULL, NULL),
       ( 'onAfterCampaignDelete', 1, 'Camapign', NULL, NULL),
       ( 'onBeforeProgramCreate', 1, 'Program', NULL, NULL),
       ( 'onAfterProgramCreate', 1, 'Program', NULL, NULL),
       ( 'onBeforeProgramChange', 1, 'Program', NULL, NULL),
       ( 'onAfterProgramChange', 1, 'Program', NULL, NULL),
       ( 'onBeforeProgramDelete', 1, 'Program', NULL, NULL),
       ( 'onAfterProgramDelete', 1, 'Program', NULL, NULL),
       ( 'onBeforeLoad', 1, 'Form', NULL, NULL),
       ( 'onLoad', 1, 'Form', NULL, NULL),
       ( 'onJSReady', 1, 'Form', NULL, NULL),
       ( 'onJSOpts', 1, 'Form', NULL, NULL),
       ( 'onCanEditGroup', 1, 'Form', NULL, NULL),
       ( 'onBeforeProcess', 1, 'Form', NULL, NULL),
       ( 'onBeforeStore', 1, 'Form', NULL, NULL),
       ( 'onBeforeCalculations', 1, 'Form', NULL, NULL),
       ( 'onAfterProcess', 1, 'Form', NULL, NULL),
       ( 'onError', 1, 'Form', NULL, NULL),
       ( 'getTopContent', 1, 'Form', NULL, NULL),
       ( 'getBottomContent', 1, 'Form', NULL, NULL),
       ( 'getEndContent', 1, 'Form', NULL, NULL),
       ( 'onDeleteRowsForm', 1, 'Form', NULL, NULL),
       ( 'onAfterDeleteRowsForm', 1, 'Form', NULL, NULL),
       ( 'onSavePage', 1, 'Form', NULL, NULL),
       ( 'onElementCanUse', 1, 'Form', NULL, NULL),
       ( 'onElementCanView', 1, 'Form', NULL, NULL),
       ( 'onBeforeEmailChange', 1, 'Email', NULL, NULL),
       ( 'onAfterEmailChange', 1, 'Email', NULL, NULL),
       ( 'onBeforeEmailCreate', 1, 'Email', NULL, NULL),
       ( 'onAfterEmailCreate', 1, 'Email', NULL, NULL),
       ( 'onBeforeEmailDelete', 1, 'Email', NULL, NULL),
       ( 'onAfterEmailDelete', 1, 'Email', NULL, NULL),
       ( 'onBeforeTagChange', 1, 'Tag', NULL, NULL),
       ( 'onAfterTagChange', 1, 'Tag', NULL, NULL),
       ( 'onBeforePdfExport', 1, 'Export', NULL, NULL),
       ( 'onAfterPdfExport', 1, 'Export', NULL, NULL),
       ( 'onBeforeExcelExport', 1, 'Export', NULL, NULL),
       ( 'onAfterExcelExport', 1, 'Export', NULL, NULL),
       ( 'onBeforeZipExport', 1, 'Export', NULL, NULL),
       ( 'onAfterZipExport', 1, 'Export', NULL, NULL),
       ( 'onBeforeLetterExport', 1, 'Export', NULL, NULL),
       ( 'onAfterLetterExport', 1, 'Export', NULL, NULL),
       ( 'onBeforeEmailSend', 1, 'Email', NULL, NULL),
       ( 'onAfterEmailSend', 1, 'Email', NULL, NULL),
       ( 'onBeforeCommentChange', 1, 'Comment', NULL, NULL),
       ( 'onAfterCommentChange', 1, 'Comment', NULL, NULL),
       ( 'onBeforeDocumentCreate', 1, 'Document', NULL, NULL),
       ( 'onAfterDocumentCreate', 1, 'Document', NULL, NULL),
       ( 'onBeforeDocumentDelete', 1, 'Document', NULL, NULL),
       ( 'onAfterDocumentDelete', 1, 'Document', NULL, NULL),
       ( 'onCreateNewFile', 1, 'File', NULL, NULL),
       ( 'onExportFiles', 1, 'Export', NULL, NULL);