-- insert new tag --
INSERT INTO jos_emundus_setup_tags (tag, request, description, published) VALUES ('QUICK MESSAGE', 'php|require_once (JPATH_SITE.DS.''components''.DS.''com_emundus''.DS.''models''.DS.''messages.php'');
$m_messages = new EmundusModelMessages();
$fnum = ''[FNUM]'';
if (!empty($fnum)) {
    $_messages = $m_messages->getActionByFnum($fnum);
    if($_messages == true) {
        return "<button type=''button'' style=''background:unset'' class=''send-emails-btn''id=candidat_". $fnum . ''>'' . "<i class=''em-send-email fa fa-envelope-open-text fa-2x'' id=" . $fnum . "></i></button>";
    } else {
    }
}', 'Send results to candidat', 1);

-- new module with published = 0 by default --
INSERT INTO jos_modules (title, note, content, ordering, position, checked_out, checked_out_time, publish_up, publish_down, published, module, access, showtitle, params, client_id, language) VALUES ('MESSAGE INSTANTANÉ', '', '<p style="text-align: center;">[QUICK MESSAGE]</p>', 1, '', 0, null, null, null, 0, 'mod_emundus_custom', 1, 1, '{"prepare_content":0,"layout":"_:default","moduleclass_sfx":"","cache":1,"cache_time":900,"cachemode":"static","module_tag":"div","bootstrap_size":"0","header_tag":"h3","header_class":"","style":"0"}', 0, '*');

-- new fabrik element attaching email ... letter --
INSERT INTO jos_fabrik_elements (name, plugin, label, checked_out, checked_out_time, created, created_by, created_by_alias, modified, modified_by, width, height, `default`, hidden, eval, ordering, show_in_list_summary, filter_type, filter_exact_match, published, link_to_detail, primary_key, auto_increment, access, use_in_page_title, parent_id, params) VALUES ('email_id', 'databasejoin', 'Email', 0, null, '2021-06-30 13:18:21', 62, 'sysadmin', '2021-06-30 13:20:04', 62, 0, 0, '', 0, 0, 6, 1, '', 1, 1, 0, 0, 0, 1, 0, 0, '{"database_join_display_type":"dropdown","join_conn_id":"1","join_db_name":"jos_emundus_setup_emails","join_key_column":"id","join_val_column":"subject","join_val_column_concat":"","database_join_where_sql":"","database_join_where_access":"1","database_join_where_when":"3","databasejoin_where_ajax":"0","databasejoin_where_ajax_default_eval":"","database_join_filter_where_sql":"","database_join_show_please_select":"1","database_join_noselectionvalue":"","database_join_noselectionlabel":"","placeholder":"","databasejoin_popupform":"35","fabrikdatabasejoin_frontend_add":"0","join_popupwidth":"","databasejoin_readonly_link":"0","fabrikdatabasejoin_frontend_select":"0","advanced_behavior":"0","dbjoin_options_per_row":"4","dbjoin_multiselect_max":"0","dbjoin_multilist_size":"6","dbjoin_autocomplete_size":"20","dbjoin_autocomplete_rows":"10","bootstrap_class":"input-large","dabase_join_label_eval":"","join_desc_column":"","dbjoin_autocomplete_how":"contains","clean_concat":"0","show_in_rss_feed":"0","show_label_in_rss_feed":"0","use_as_rss_enclosure":"0","rollover":"","tipseval":"0","tiplocation":"top-left","labelindetails":"0","labelinlist":"0","comment":"","edit_access":"1","edit_access_user":"","view_access":"1","view_access_user":"","list_view_access":"1","encrypt":"0","store_in_db":"1","default_on_copy":"0","can_order":"0","alt_list_heading":"","custom_link":"","custom_link_target":"","custom_link_indetails":"1","use_as_row_class":"0","include_in_list_query":"1","always_render":"0","icon_folder":"0","icon_hovertext":"1","icon_file":"","icon_subdir":"","filter_length":"20","filter_access":"1","full_words_only":"0","filter_required":"0","filter_build_method":"0","filter_groupby":"text","inc_in_adv_search":"1","filter_class":"input-medium","filter_responsive_class":"","tablecss_header_class":"","tablecss_header":"","tablecss_cell_class":"","tablecss_cell":"","sum_on":"0","sum_label":"Sum","sum_access":"1","sum_split":"","avg_on":"0","avg_label":"Average","avg_access":"1","avg_round":"0","avg_split":"","median_on":"0","median_label":"Median","median_access":"1","median_split":"","count_on":"0","count_label":"Count","count_condition":"","count_access":"1","count_split":"","custom_calc_on":"0","custom_calc_label":"Custom","custom_calc_query":"","custom_calc_access":"1","custom_calc_split":"","custom_calc_php":"","validations":[]}');