-- INSERT SOURCERER INTO THE EXTENISON TABLE
INSERT INTO jos_extensions (package_id, name, type, element, folder, client_id, enabled, access, protected, manifest_cache, params, custom_data, system_data, checked_out, checked_out_time, ordering, state) VALUES (0, 'Regular Labs Library', 'library', 'regularlabs', '', 0, 1, 1, 0, '{"name":"Regular Labs Library","type":"library","creationDate":"September 2021","author":"Regular Labs (Peter van Westen)","copyright":"Copyright \\u00a9 2021 Regular Labs - All Rights Reserved","authorEmail":"info@regularlabs.com","authorUrl":"https:\\/\\/regularlabs.com","version":"21.9.16879","description":"Regular Labs Library - used by Regular Labs extensions","group":"","filename":"regularlabs"}', '{}', '', '', 0, '2021-10-15 07:36:20', 0, 0);
INSERT INTO jos_extensions (package_id, name, type, element, folder, client_id, enabled, access, protected, manifest_cache, params, custom_data, system_data, checked_out, checked_out_time, ordering, state) VALUES (0, 'PLG_SYSTEM_SOURCERER', 'plugin', 'sourcerer', 'system', 0, 1, 1, 0, '{"name":"PLG_SYSTEM_SOURCERER","type":"plugin","creationDate":"September 2021","author":"Regular Labs (Peter van Westen)","copyright":"Copyright \\u00a9 2021 Regular Labs - All Rights Reserved","authorEmail":"info@regularlabs.com","authorUrl":"https:\\/\\/regularlabs.com","version":"9.0.2","description":"PLG_SYSTEM_SOURCERER_DESC","group":"","filename":"sourcerer"}', '{"enable_css":"1","enable_js":"1","enable_php":"1","forbidden_php":"dl, escapeshellarg, escapeshellcmd, exec, passthru, popen, proc_close, proc_open, shell_exec, symlink, system","forbidden_tags":"","@wizard":"0","button_text":"Code","enable_frontend":"1","syntax_word":"source","tag_characters":"{.}","trim":"0","enable_in_head":"0","remove_from_search":"0","include_path":"\\/","tmp_path":"","place_comments":"1"}', '', '', 0, '2021-10-20 13:43:28', 0, 0);
SET @sourcerer_id_1 := LAST_INSERT_ID();
INSERT INTO jos_extensions (package_id, name, type, element, folder, client_id, enabled, access, protected, manifest_cache, params, custom_data, system_data, checked_out, checked_out_time, ordering, state) VALUES (0, 'PLG_EDITORS-XTD_SOURCERER', 'plugin', 'sourcerer', 'editors-xtd', 0, 1, 1, 0, '{"name":"PLG_EDITORS-XTD_SOURCERER","type":"plugin","creationDate":"September 2021","author":"Regular Labs (Peter van Westen)","copyright":"Copyright \\u00a9 2021 Regular Labs - All Rights Reserved","authorEmail":"info@regularlabs.com","authorUrl":"https:\\/\\/regularlabs.com","version":"9.0.2","description":"PLG_EDITORS-XTD_SOURCERER_DESC","group":"","filename":"sourcerer"}', '[]', '', '', 0, '2021-10-20 13:43:28', 0, 0);
SET @sourcerer_id_2 := LAST_INSERT_ID();

-- INSERT SOURCERER INTO THE jos_update_sites TABLE
INSERT INTO jos_update_sites (name, type, location, enabled, last_check_timestamp, extra_query) VALUES ('Regular Labs - Sourcerer', 'extension', 'https://download.regularlabs.com/updates.xml?e=sourcerer&type=.xml', 1, 0, '');
SET @sourcerer__update_id := LAST_INSERT_ID();

-- INSERT ALL INTO THE jos_update_sites_extensions TABLE
INSERT INTO jos_update_sites_extensions (update_site_id, extension_id) VALUES (@sourcerer__update_id, @sourcerer_id_1);
INSERT INTO jos_update_sites_extensions (update_site_id, extension_id) VALUES (@sourcerer__update_id, @sourcerer_id_2);