INSERT IGNORE INTO `#__hikashop_currency` (`currency_id`, `currency_symbol`, `currency_code`, `currency_format`, `currency_name`, `currency_published`, `currency_displayed`, `currency_locale`) VALUES
(1, '€', 'EUR', '%n', 'Euro', 1,1, 'a:13:{s:17:"mon_decimal_point";s:1:",";s:17:"mon_thousands_sep";s:1:".";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:0;s:14:"p_sep_by_space";i:1;s:13:"n_cs_precedes";i:0;s:14:"n_sep_by_space";i:1;s:11:"p_sign_posn";i:1;s:11:"n_sign_posn";i:1;}'),
(2, '\$', 'USD', '%n', 'United States dollar', 1, 1, 'a:13:{s:17:"mon_decimal_point";s:1:".";s:17:"mon_thousands_sep";s:1:",";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:1;s:14:"p_sep_by_space";i:0;s:13:"n_cs_precedes";i:1;s:14:"n_sep_by_space";i:0;s:11:"p_sign_posn";i:4;s:11:"n_sign_posn";i:4;}'),
(3, '¥', 'JPY', '%n', 'Japanese yen', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:",";s:17:"mon_thousands_sep";s:1:" ";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:0;s:11:"frac_digits";i:0;s:13:"p_cs_precedes";i:0;s:14:"p_sep_by_space";i:1;s:13:"n_cs_precedes";i:0;s:14:"n_sep_by_space";i:1;s:11:"p_sign_posn";i:1;s:11:"n_sign_posn";i:1;}'),
(4, '£', 'GBP', '%n', 'British pound', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:".";s:17:"mon_thousands_sep";s:1:",";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:1;s:14:"p_sep_by_space";i:1;s:13:"n_cs_precedes";i:1;s:14:"n_sep_by_space";i:1;s:11:"p_sign_posn";i:1;s:11:"n_sign_posn";i:1;}'),
(5, '\$', 'CAD', '%i', 'Canadian dollar', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:".";s:17:"mon_thousands_sep";s:1:",";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:1;s:14:"p_sep_by_space";i:0;s:13:"n_cs_precedes";i:1;s:14:"n_sep_by_space";i:0;s:11:"p_sign_posn";i:4;s:11:"n_sign_posn";i:4;}'),
(6, '\$', 'AUD', '%i', 'Australian dollar', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:".";s:17:"mon_thousands_sep";s:1:",";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:1;s:14:"p_sep_by_space";i:0;s:13:"n_cs_precedes";i:1;s:14:"n_sep_by_space";i:0;s:11:"p_sign_posn";i:4;s:11:"n_sign_posn";i:4;}'),
(7, '\$', 'NZD', '%i', 'New Zealand dollar', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:",";s:17:"mon_thousands_sep";s:1:".";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:2;s:11:"frac_digits";i:2;s:13:"p_cs_precedes";i:1;s:14:"p_sep_by_space";i:0;s:13:"n_cs_precedes";i:1;s:14:"n_sep_by_space";i:0;s:11:"p_sign_posn";i:4;s:11:"n_sign_posn";i:4;}'),
(8, '؋', 'AFN', '%i', 'Afghan afghani', 0, 0, ''),
(9, 'Lek', 'ALL', '%i', 'Albanian lek', 0, 0, ''),
(10, 'د.ج', 'DZD', '%i', 'Algerian dinar', 0, 0, ''),
(11, 'Kz ', 'AOA', '%i', 'Angolan kwanza', 0, 0, ''),
(12, '\$', 'ARS', '%i', 'Argentine peso', 0, 0, ''),
(13, 'դր.', 'AMD', '%i', 'Armenian dram', 0, 0, ''),
(14, 'ƒ', 'AWG', '%i', 'Aruban florin', 0, 0, ''),
(15, 'ман', 'AZN', '%i', 'Azerbaijani manat', 0, 0, ''),
(16, '\$', 'BSD', '%i', 'Bahamian dollar', 0, 0, ''),
(17, 'ب.د', 'BHD', '%i', 'Bahraini dinar', 0, 0, ''),
(18, '৳', 'BDT', '%i', 'Bangladeshi taka', 0, 0, ''),
(19, '\$', 'BBD', '%i', 'Barbadian dollar', 0, 0, ''),
(20, 'p.', 'BYR', '%i', 'Belarusian ruble', 0, 0, ''),
(21, 'BZ\$', 'BZD', '%i', 'Belize dollar', 0, 0, ''),
(22, '\$', 'BMD', '%i', 'Bermudian dollar', 0, 0, ''),
(23, 'BTN', 'BTN', '%i', 'Bhutanese ngultrum', 0, 0, ''),
(24, '\$b', 'BOB', '%i', 'Bolivian boliviano', 0, 0, ''),
(25, 'XBA', 'XBA', '%i', 'Bond Markets', 0, 0, ''),
(26, 'KM', 'BAM', '%i', 'Bosnia and Herzegovina convert', 0, 0, ''),
(27, 'P', 'BWP', '%i', 'Botswana pula', 0, 0, ''),
(28, 'R$', 'BRL', '%i', 'Brazilian real', 0, 0, ''),
(29, '\$', 'BND', '%i', 'Brunei dollar', 0, 0, ''),
(30, 'лв', 'BGN', '%i', 'Bulgarian lev', 0, 0, ''),
(31, 'Fr ', 'BIF', '%i', 'Burundian franc', 0, 0, ''),
(32, '៛', 'KHR', '%i', 'Cambodian riel', 0, 0, ''),
(33, '\$', 'CVE', '%i', 'Cape Verdean escudo', 0, 0, ''),
(34, '\$', 'KYD', '%i', 'Cayman Islands dollar', 0, 0, ''),
(35, 'Fr ', 'XAF', '%i', 'Central African CFA franc', 0, 0, ''),
(36, 'Fr ', 'XPF', '%i', 'CFP franc', 0, 0, ''),
(37, '\$', 'CLP', '%i', 'Chilean peso', 0, 0, ''),
(38, '元', 'CNY', '%i', 'Chinese renminbi yuan', 0, 0, ''),
(39, 'XTS', 'XTS', '%i', 'Codes specif', 0, 0, ''),
(40, '\$', 'COP', '%i', 'Colombian peso', 0, 0, ''),
(41, 'Fr ', 'KMF', '%i', 'Comorian franc', 0, 0, ''),
(42, 'Fr ', 'CDF', '%i', 'Congolese franc', 0, 0, ''),
(43, '₡', 'CRC', '%i', 'Costa Rican colón', 0, 0, ''),
(44, 'kn', 'HRK', '%i', 'Croatian kuna', 0, 0, ''),
(45, '₱', 'CUP', '%i', 'Cuban peso', 0, 0, ''),
(46, 'Kč', 'CZK', '%i', 'Czech koruna', 0, 0, ''),
(47, 'kr', 'DKK', '%i', 'Danish krone', 0, 0, ''),
(48, 'Fr ', 'DJF', '%i', 'Djiboutian franc', 0, 0, ''),
(49, 'RD\$', 'DOP', '%i', 'Dominican peso', 0, 0, ''),
(50, '\$', 'XCD', '%i', 'East Caribbean dollar', 0, 0, ''),
(51, '£', 'EGP', '%i', 'Egyptian pound', 0, 0, ''),
(52, 'Nfk ', 'ERN', '%i', 'Eritrean nakfa', 0, 0, ''),
(53, 'kr', 'EEK', '%i', 'Estonian kroon', 0, 0, ''),
(54, 'ETB', 'ETB', '%i', 'Ethiopian birr', 0, 0, ''),
(55, 'XBB', 'XBB', '%i', 'European Mon', 0, 0, ''),
(56, 'XBD', 'XBD', '%i', 'European Uni', 0, 0, ''),
(57, 'XBC', 'XBC', '%i', 'European Uni', 0, 0, ''),
(58, '£', 'FKP', '%i', 'Falkland pound', 0, 0, ''),
(59, '$', 'FJD', '%i', 'Fijian dollar', 0, 0, ''),
(60, 'D ', 'GMD', '%i', 'Gambian dalasi', 0, 0, ''),
(61, 'ლ', 'GEL', '%i', 'Georgian lari', 0, 0, ''),
(62, '₵', 'GHS', '%i', 'Ghanaian cedi', 0, 0, ''),
(63, '£', 'GIP', '%i', 'Gibraltar pound', 0, 0, ''),
(64, 'Gold', 'XAU', '%i', 'Gold', 0, 0, ''),
(65, 'Q', 'GTQ', '%i', 'Guatemalan quetzal', 0, 0, ''),
(66, 'GWP', 'GWP', '%i', 'Guinea-Bissa', 0, 0, ''),
(67, 'Fr ', 'GNF', '%i', 'Guinean franc', 0, 0, ''),
(68, '$', 'GYD', '%i', 'Guyanese dollar', 0, 0, ''),
(69, 'G ', 'HTG', '%i', 'Haitian gourde', 0, 0, ''),
(70, 'L', 'HNL', '%i', 'Honduran lempira', 0, 0, ''),
(71, '元', 'HKD', '%i', 'Hong Kong dollar', 0, 0, ''),
(72, 'Ft', 'HUF', '%i', 'Hungarian forint', 0, 0, ''),
(73, 'kr', 'ISK', '%i', 'Icelandic króna', 0, 0, ''),
(74, '₨', 'INR', '%i', 'Indian rupee', 0, 0, ''),
(75, 'Rp', 'IDR', '%i', 'Indonesian rupiah', 0, 0, ''),
(76, '﷼', 'IRR', '%i', 'Iranian rial', 0, 0, ''),
(77, 'ع.د', 'IQD', '%i', 'Iraqi dinar', 0, 0, ''),
(78, '₪', 'ILS', '%n', 'Israeli new sheqel', 0, 0, 'a:13:{s:17:"mon_decimal_point";s:1:",";s:17:"mon_thousands_sep";s:0:"";s:12:"mon_grouping";s:1:"3";s:13:"positive_sign";s:0:"";s:13:"negative_sign";s:1:"-";s:15:"int_frac_digits";i:0;s:11:"frac_digits";i:0;s:13:"p_cs_precedes";i:0;s:14:"p_sep_by_space";i:1;s:13:"n_cs_precedes";i:0;s:14:"n_sep_by_space";i:1;s:11:"p_sign_posn";i:1;s:11:"n_sign_posn";i:1;}'),
(79, 'J$', 'JMD', '%i', 'Jamaican dollar', 0, 0, ''),
(80, 'د.ا', 'JOD', '%i', 'Jordanian dinar', 0, 0, ''),
(81, 'лв', 'KZT', '%i', 'Kazakhstani tenge', 0, 0, ''),
(82, 'Sh ', 'KES', '%i', 'Kenyan shilling', 0, 0, ''),
(83, 'د.ك', 'KWD', '%i', 'Kuwaiti dinar', 0, 0, ''),
(84, 'лв', 'KGS', '%i', 'Kyrgyzstani som', 0, 0, ''),
(85, '₭', 'LAK', '%i', 'Lao kip', 0, 0, ''),
(86, 'Ls', 'LVL', '%i', 'Latvian lats', 0, 0, ''),
(87, '£', 'LBP', '%i', 'Lebanese pound', 0, 0, ''),
(88, 'L ', 'LSL', '%i', 'Lesotho loti', 0, 0, ''),
(89, '$', 'LRD', '%i', 'Liberian dollar', 0, 0, ''),
(90, 'ل.د', 'LYD', '%i', 'Libyan dinar', 0, 0, ''),
(91, 'Lt', 'LTL', '%i', 'Lithuanian litas', 0, 0, ''),
(92, 'P ', 'MOP', '%i', 'Macanese pataca', 0, 0, ''),
(93, 'ден', 'MKD', '%i', 'Macedonian denar', 0, 0, ''),
(94, 'MGA', 'MGA', '%i', 'Malagasy ariary', 0, 0, ''),
(95, 'MK ', 'MWK', '%i', 'Malawian kwacha', 0, 0, ''),
(96, 'RM', 'MYR', '%i', 'Malaysian ringgit', 0, 0, ''),
(97, 'ރ.', 'MVR', '%i', 'Maldivian rufiyaa', 0, 0, ''),
(98, 'UM ', 'MRO', '%i', 'Mauritanian ouguiya', 0, 0, ''),
(99, '₨', 'MUR', '%i', 'Mauritian rupee', 0, 0, ''),
(100, '\$', 'MXN', '%i', 'Mexican peso', 0, 0, ''),
(101, 'MXV', 'MXV', '%i', 'Mexican Unid', 0, 0, ''),
(102, 'L ', 'MDL', '%i', 'Moldovan leu', 0, 0, ''),
(103, '₮', 'MNT', '%i', 'Mongolian tögrög', 0, 0, ''),
(104, 'د.م.', 'MAD', '%i', 'Moroccan dirham', 0, 0, ''),
(105, 'MT', 'MZN', '%i', 'Mozambican metical', 0, 0, ''),
(106, 'BOV', 'BOV', '%i', 'Mvdol', 0, 0, ''),
(107, 'K ', 'MMK', '%i', 'Myanmar kyat', 0, 0, ''),
(108, '\$', 'NAD', '%i', 'Namibian dollar', 0, 0, ''),
(109, '₨', 'NPR', '%i', 'Nepalese rupee', 0, 0, ''),
(110, 'ƒ', 'ANG', '%i', 'Netherlands Antillean gulden', 0, 0, ''),
(111, 'NT\$', 'TWD', '%i', 'New Taiwan dollar', 0, 0, ''),
(112, 'C\$', 'NIO', '%i', 'Nicaraguan córdoba', 0, 0, ''),
(113, '₦', 'NGN', '%i', 'Nigerian naira', 0, 0, ''),
(114, '₩', 'KPW', '%i', 'North Korean won', 0, 0, ''),
(115, 'kr', 'NOK', '%i', 'Norwegian krone', 0, 0, ''),
(116, '﷼', 'OMR', '%i', 'Omani rial', 0, 0, ''),
(117, '₨', 'PKR', '%i', 'Pakistani rupee', 0, 0, ''),
(118, 'XPD', 'XPD', '%i', 'Palladium', 0, 0, ''),
(119, 'B/.', 'PAB', '%i', 'Panamanian balboa', 0, 0, ''),
(120, 'K ', 'PGK', '%i', 'Papua New Guinean kina', 0, 0, ''),
(121, '₲', 'PYG', '%i', 'Paraguayan guaraní', 0, 0, ''),
(122, 'S/.', 'PEN', '%i', 'Peruvian nuevo sol', 0, 0, ''),
(123, '₱', 'PHP', '%i', 'Philippine peso', 0, 0, ''),
(124, 'XPT', 'XPT', '%i', 'Platinum', 0, 0, ''),
(125, 'zł', 'PLN', '%i', 'Polish Złoty', 0, 0, ''),
(126, '﷼', 'QAR', '%i', 'Qatari riyal', 0, 0, ''),
(127, 'lei', 'RON', '%i', 'Romanian leu', 0, 0, ''),
(128, 'руб', 'RUB', '%i', 'Russian ruble', 0, 0, ''),
(129, 'Fr ', 'RWF', '%i', 'Rwandan franc', 0, 0, ''),
(130, '£', 'SHP', '%i', 'Saint Helenian pound', 0, 0, ''),
(131, '$', 'SVC', '%i', 'Salvadoran colón', 0, 0, ''),
(132, 'T ', 'WST', '%i', 'Samoan tala', 0, 0, ''),
(133, 'Db ', 'STD', '%i', 'São Tomé and Príncipe dobra', 0, 0, ''),
(134, '﷼', 'SAR', '%i', 'Saudi riyal', 0, 0, ''),
(135, 'XDR', 'XDR', '%i', 'SDR', 0, 0, ''),
(136, 'Дин.', 'RSD', '%i', 'Serbian dinar', 0, 0, ''),
(137, '₨', 'SCR', '%i', 'Seychellois rupee', 0, 0, ''),
(138, 'Le ', 'SLL', '%i', 'Sierra Leonean leone', 0, 0, ''),
(139, 'XAG', 'XAG', '%i', 'Silver', 0, 0, ''),
(140, '\$', 'SGD', '%i', 'Singapore dollar', 0, 0, ''),
(141, 'Sk ', 'SKK', '%i', 'Slovak koruna', 0, 0, ''),
(142, '\$', 'SBD', '%i', 'Solomon Islands dollar', 0, 0, ''),
(143, 'S', 'SOS', '%i', 'Somali shilling', 0, 0, ''),
(144, 'R', 'ZAR', '%i', 'South African rand', 0, 0, ''),
(145, '₩', 'KRW', '%i', 'South Korean won', 0, 0, ''),
(146, '₨', 'LKR', '%i', 'Sri Lankan rupee', 0, 0, ''),
(147, '£ ', 'SDG', '%i', 'Sudanese pound', 0, 0, ''),
(148, '$', 'SRD', '%i', 'Surinamese dollar', 0, 0, ''),
(149, 'L ', 'SZL', '%i', 'Swazi lilangeni', 0, 0, ''),
(150, 'kr', 'SEK', '%i', 'Swedish krona', 0, 0, ''),
(151, 'CHF', 'CHF', '%i', 'Swiss franc', 0, 0, ''),
(152, '£', 'SYP', '%i', 'Syrian pound', 0, 0, ''),
(153, 'ЅМ', 'TJS', '%i', 'Tajikistani somoni', 0, 0, ''),
(154, 'Sh ', 'TZS', '%i', 'Tanzanian shilling', 0, 0, ''),
(155, '฿', 'THB', '%i', 'Thai baht', 0, 0, ''),
(156, 'XXX', 'XXX', '%i', 'The codes as', 0, 0, ''),
(157, 'T$ ', 'TOP', '%i', 'Tongan paʻanga', 0, 0, ''),
(158, 'TT$', 'TTD', '%i', 'Trinidad and Tobago dollar', 0, 0, ''),
(159, 'د.ت', 'TND', '%i', 'Tunisian dinar', 0, 0, ''),
(160, 'YTL', 'TRY', '%i', 'Turkish new lira', 0, 0, ''),
(161, 'm ', 'TMM', '%i', 'Turkmenistani manat', 0, 0, ''),
(162, 'Sh ', 'UGX', '%i', 'Ugandan shilling', 0, 0, ''),
(163, 'XFU', 'XFU', '%i', 'UIC-Franc', 0, 0, ''),
(164, '₴', 'UAH', '%i', 'Ukrainian hryvnia', 0, 0, ''),
(165, 'COU', 'COU', '%i', 'Unidad de Va', 0, 0, ''),
(166, 'CLF', 'CLF', '%i', 'Unidades de ', 0, 0, ''),
(167, 'د.إ', 'AED', '%i', 'United Arab Emirates dirham', 0, 0, ''),
(168, 'UYI', 'UYI', '%i', 'Uruguay Peso', 0, 0, ''),
(169, '\$', 'UYU', '%i', 'Uruguayan peso', 0, 0, ''),
(170, '\$', 'USN', '%i', 'US Dollar (Next Day)', 0, 0, ''),
(171, '\$', 'USS', '%i', 'US Dollar (Second Day)', 0, 0, ''),
(172, 'лв', 'UZS', '%i', 'Uzbekistani som', 0, 0, ''),
(173, 'Vt ', 'VUV', '%i', 'Vanuatu vatu', 0, 0, ''),
(174, 'Bs', 'VEF', '%i', 'Venezuelan bolívar', 0, 0, ''),
(175, '₫', 'VND', '%i', 'Vietnamese Dong', 0, 0, ''),
(176, 'Fr ', 'XOF', '%i', 'West African CFA franc', 0, 0, ''),
(177, '€', 'CHE', '%i', 'WIR Euro', 0, 0, ''),
(178, 'CHW', 'CHW', '%i', 'WIR Franc', 0, 0, ''),
(179, '﷼', 'YER', '%i', 'Yemeni rial', 0, 0, ''),
(180, 'ZK ', 'ZMW', '%i', 'Zambian kwacha', 0, 0, ''),
(181, 'Z\$', 'ZWD', '%i', 'Zimbabwean dollar', 0, 0, ''),
(182, 'p.', 'BYN', '%i', 'Belarusian ruble', 0, 0, '');