name: 22
timestamp: 1635347591
version: 7
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: _joomla_-_gantry4
  timestamp: 1530009501
positions:
  top-b: 'Top B'
  top-c: 'Top C'
  header-a: 'Header A'
  header-b: Header-b
  header-c: 'Header C'
  breadcrumb: Breadcrumb
  drawer: Drawer
  drawer-a: 'Drawer A'
  drawer-b: 'Drawer B'
  drawer-c: 'Drawer C'
  content-top-a: content-top-a
  content-top-b: content-top-b
  content-top-c: content-top-c
  content-bottom-a: content-bottom-a
  content-bottom-b: content-bottom-b
  content-bottom-c: content-bottom-c
  sidebar-a: 'Sidebar A'
  sidebar-b: 'Sidebar B'
  sidebar-c: 'Sidebar C'
  bottom-a: bottom-a
  bottom-b: bottom-b
  bottom-c: bottom-c
  footer-a: footer-a
  footer-b: footer-b
  footer-rgpd: footer-rgpd
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  utility: Utility
  breadcrumb: Breadcrumb
  maintop: Maintop
  mainbottom: Mainbottom
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  main-mainbody: Mainbody
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-1425: 'Top B'
    position-position-7444: 'Top C'
    position-position-3622: 'Header A'
    position-position-7200: Header-b
    position-position-3358: 'Header C'
    position-position-5474: Breadcrumb
    position-position-1995: Drawer
    position-position-8613: 'Drawer A'
    position-position-2424: 'Drawer B'
    position-position-5975: 'Drawer C'
    position-position-7864: content-top-a
    position-position-1758: content-top-b
    position-position-7871: content-top-c
    position-position-1871: content-bottom-a
    position-position-9368: content-bottom-b
    position-position-1384: content-bottom-c
    position-position-2430: 'Sidebar A'
    position-position-2407: 'Sidebar B'
    position-position-9126: 'Sidebar C'
    position-position-7739: bottom-a
    position-position-2688: bottom-b
    position-position-4367: bottom-c
    position-position-2232: footer-a
    position-position-8709: footer-b
    position-position-9183: footer-rgpd
  messages:
    system-messages-2924: 'System Messages'
  content:
    system-content-5664: 'Page Content'
  branding:
    branding-7645: Branding
  module:
    position-module-9965: 'Mobile Menu'
    position-module-2365: 'User menu phone'
inherit:
  default:
    drawer: drawer
    top: top
    navigation: navigation
    showcase: showcase
    feature: feature
    utility: utility
    breadcrumb: breadcrumb
    maintop: maintop
    main-mainbody: main-mainbody
    sidebar: sidebar
    mainbottom: mainbottom
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-1425: position-position-4408
    position-position-7444: position-position-7532
    position-position-3622: position-position-6276
    position-position-7200: position-position-5691
    position-position-3358: position-position-5235
    position-position-5474: position-position-6366
    system-messages-2924: system-messages-7972
    position-position-1995: position-position-6313
    position-position-8613: position-position-3312
    position-position-2424: position-position-3137
    position-position-5975: position-position-3100
    position-position-7864: position-position-8748
    position-position-1758: position-position-8389
    position-position-7871: position-position-2887
    system-content-5664: system-content-4895
    position-position-1871: position-position-1822
    position-position-9368: position-position-8774
    position-position-1384: position-position-3185
    position-position-2430: position-position-8186
    position-position-2407: position-position-9360
    position-position-9126: position-position-3949
    position-position-7739: position-position-3854
    position-position-2688: position-position-8649
    position-position-4367: position-position-5181
    position-position-2232: position-position-6744
    position-position-8709: position-position-8794
    position-module-9965: position-module-2455
    position-module-2365: position-module-3093
