name: 24
timestamp: 1674736897
version: 7
preset:
  image: 'gantry-admin://images/layouts/3-col.png'
  name: _joomla_-_gantry4
  timestamp: 1530009501
positions:
  breadcrumb: Breadcrumb
  drawer: Drawer
  drawer-a: 'Drawer A'
  drawer-b: 'Drawer B'
  drawer-c: 'Drawer C'
  top-b: 'Top B'
  top-c: 'Top C'
  header-a: 'Header A'
  header-b: Header-b
  header-c: 'Header C'
  content-top-a: content-top-a
  content-top-b: content-top-b
  content-top-c: content-top-c
  content-bottom-a: content-bottom-a
  content-bottom-b: content-bottom-b
  content-bottom-c: content-bottom-c
  sidebar-a: 'Sidebar A'
  sidebar-b: 'Sidebar B'
  sidebar-c: 'Sidebar C'
  bottom-a: bottom-a
  bottom-b: bottom-b
  bottom-c: bottom-c
  footer-a: footer-a
  footer-b: footer-b
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  utility: Utility
  breadcrumb: Breadcrumb
  maintop: Maintop
  mainbottom: Mainbottom
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  main-mainbody: Mainbody
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-6366: Breadcrumb
    position-position-6313: Drawer
    position-position-3312: 'Drawer A'
    position-position-3137: 'Drawer B'
    position-position-3100: 'Drawer C'
    position-position-7247: 'Top B'
    position-position-8952: 'Top C'
    position-position-6163: 'Header A'
    position-position-8834: Header-b
    position-position-3982: 'Header C'
    position-position-8311: content-top-a
    position-position-4520: content-top-b
    position-position-9607: content-top-c
    position-position-5676: content-bottom-a
    position-position-8167: content-bottom-b
    position-position-2088: content-bottom-c
    position-position-5451: 'Sidebar A'
    position-position-8730: 'Sidebar B'
    position-position-8047: 'Sidebar C'
    position-position-4325: bottom-a
    position-position-4644: bottom-b
    position-position-5854: bottom-c
    position-position-3170: footer-a
    position-position-3651: footer-b
  messages:
    system-messages-7972: 'System Messages'
  content:
    system-content-8269: 'Page Content'
  module:
    position-module-2211: 'Mobile Menu'
    position-module-4659: 'User menu phone'
inherit:
  default:
    drawer: drawer
    top: top
    navigation: navigation
    breadcrumb: breadcrumb
    maintop: maintop
    main-mainbody: main-mainbody
    sidebar: sidebar
    mainbottom: mainbottom
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-7247: position-position-4408
    position-position-8952: position-position-7532
    position-position-6163: position-position-6276
    position-position-8834: position-position-5691
    position-position-3982: position-position-5235
    position-position-8311: position-position-8748
    position-position-4520: position-position-8389
    position-position-9607: position-position-2887
    system-content-8269: system-content-4895
    position-position-5676: position-position-1822
    position-position-8167: position-position-8774
    position-position-2088: position-position-3185
    position-position-5451: position-position-8186
    position-position-8730: position-position-9360
    position-position-8047: position-position-3949
    position-position-4325: position-position-3854
    position-position-4644: position-position-8649
    position-position-5854: position-position-5181
    position-position-3170: position-position-6744
    position-position-3651: position-position-8794
    position-module-2211: position-module-2455
    position-module-4659: position-module-3093
